<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InvKategoriPeralatan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class InvKategoriPeralatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['kode' => 'PDM-00001', 'nama' => 'PERALATAN DAN MESIN'],
            ['kode' => 'AB-00002', 'nama' => 'ALAT BESAR'],
            ['kode' => 'ABD-00003', 'nama' => 'ALAT BESAR DARAT'],
            ['kode' => 'T-00004', 'nama' => 'TRACTOR'],
            ['kode' => 'CTA-00005', 'nama' => 'CRAWLER TRACTOR + ATTACHMENT'],
            ['kode' => 'WTA-00006', 'nama' => 'WHEEL TRACTOR + ATTACHMENT'],
            ['kode' => 'STA-00007', 'nama' => 'SWAMP TRACTOR + ATTACHMENT'],
            ['kode' => 'PM-00008', 'nama' => 'PRIME MOWER'],
            ['kode' => 'ATT-00009', 'nama' => 'AIRCRAFT TOWING TRACTOR'],
            ['kode' => 'TB-00010', 'nama' => 'TOWING BAR'],
            ['kode' => 'B-00011', 'nama' => 'BULLDOZER'],
            ['kode' => 'WD-00012', 'nama' => 'WHEEL DOZER'],
            ['kode' => 'TL-00013', 'nama' => 'TRACTOR LAINNYA'],
            ['kode' => 'G-00014', 'nama' => 'GRADER'],
            ['kode' => 'GA-00015', 'nama' => 'GRADER + ATTACHMENT'],
            ['kode' => 'GTT-00016', 'nama' => 'GRADER TOWED TYPE'],
            ['kode' => 'GL-00017', 'nama' => 'GRADER LAINNYA'],
            ['kode' => 'E-00018', 'nama' => 'EXCAVATOR'],
            ['kode' => 'CEA-00019', 'nama' => 'CRAWLER EXCAVATOR + ATTACHMENT'],
            ['kode' => 'WEA-00020', 'nama' => 'WHEEL EXCAVATOR + ATTACHMENT'],
            ['kode' => 'EL-00021', 'nama' => 'EXCAVATOR LAINNYA'],
            ['kode' => 'PD-00022', 'nama' => 'PILE DRIVER'],
            ['kode' => 'DPD-00023', 'nama' => 'DIESEL PILE DRIVER'],
            ['kode' => 'PPD-00024', 'nama' => 'PNEUMATIC PILE DRIVER'],
            ['kode' => 'VPD-00025', 'nama' => 'VIBRATION PILE DRIVER'],
            ['kode' => 'PDL-00026', 'nama' => 'PILE DRIVER LAINNYA'],
            ['kode' => 'H-00027', 'nama' => 'HAULER'],
            ['kode' => 'SPS-00028', 'nama' => 'SELF PROPELLED SCRAPER'],
            ['kode' => 'TS-00029', 'nama' => 'TOWED SCRAPER'],
            ['kode' => 'DT-00030', 'nama' => 'DUMP TRUCK'],
            ['kode' => 'DW-00031', 'nama' => 'DUMP WAGON'],
            ['kode' => 'L-00032', 'nama' => 'LORI'],
            ['kode' => 'HL-00033', 'nama' => 'HAULER LAINNYA'],
            ['kode' => 'AE-00034', 'nama' => 'ASPHALT EQUIPMENT'],
            ['kode' => 'AMP-00035', 'nama' => 'ASPHALT MIXING PLANT'],
            ['kode' => 'AF-00036', 'nama' => 'ASPHALT FINISHER'],
            ['kode' => 'AD-00037', 'nama' => 'ASPHALT DISTRIBUTOR'],
            ['kode' => 'AH-00038', 'nama' => 'ASPHALT HEATER'],
            ['kode' => 'AT-00039', 'nama' => 'ASPHALT TANKER'],
            ['kode' => 'AS-00040', 'nama' => 'ASPHALT SPRAYER'],
            ['kode' => 'AD-00041', 'nama' => 'ASBUTON DRYER'],
            ['kode' => 'AR-00042', 'nama' => 'ASPHALT RECYCLE'],
            ['kode' => 'CMM-00043', 'nama' => 'COLD MILLING MACHINE'],
            ['kode' => 'AM-00044', 'nama' => 'ASPHALT MIXER'],
            ['kode' => 'B/AT-00045', 'nama' => 'BITUMEN / ASPHALT TEST'],
            ['kode' => 'AEL-00046', 'nama' => 'ASPHALT EQUIPMENT LAINNYA'],
            ['kode' => 'CE-00047', 'nama' => 'COMPACTING EQUIPMENT'],
            ['kode' => 'MRWR-00048', 'nama' => 'MACADAM ROLLER/THREE WHEEL ROLLER'],
            ['kode' => 'TR-00049', 'nama' => 'TANDEM ROLLER'],
            ['kode' => 'MR-00050', 'nama' => 'MESH ROLLER'],
            ['kode' => 'VR-00051', 'nama' => 'VIBRATION ROLLER'],
            ['kode' => 'TR-00052', 'nama' => 'TYRE ROLLER'],
            ['kode' => 'SS-00053', 'nama' => 'SOIL STABILIZER'],
            ['kode' => 'SR-00054', 'nama' => 'SHEEPFOOT/TAMPING ROLLER'],
            ['kode' => 'S-00055', 'nama' => 'STAMPER'],
            ['kode' => 'VP-00056', 'nama' => 'VIBRATION PLATE'],
            ['kode' => 'PS-00057', 'nama' => 'PEMADAT SAMPAH'],
            ['kode' => 'TBT-00058', 'nama' => 'TRUCK & BUSH TYRE'],
            ['kode' => 'CEL-00059', 'nama' => 'COMPACTING EQUIPMENT LAINNYA'],
            ['kode' => 'ACE-00060', 'nama' => 'AGGREGATE & CONCRETE EQUIPMENT'],
            ['kode' => 'SCP-00061', 'nama' => 'STONE CRUSHING PLANT'],
            ['kode' => 'SC-00062', 'nama' => 'SCREENING CLASSIFER'],
            ['kode' => 'SC-00063', 'nama' => 'STONE CHUSER'],
            ['kode' => 'AW-00064', 'nama' => 'AGGREGATE WASHER'],
            ['kode' => 'BP-00065', 'nama' => 'BATCHING PLANT'],
            ['kode' => 'CF-00066', 'nama' => 'CONCRETE FINISHER'],
            ['kode' => 'CP-00067', 'nama' => 'CONCRETE PUMP'],
            ['kode' => 'CL-00068', 'nama' => 'CONCRETE LIFT'],
            ['kode' => 'CP-00069', 'nama' => 'CONCRETE PRESTRES'],
            ['kode' => 'CC-00070', 'nama' => 'CONCRETE CUTTER'],
            ['kode' => 'CM-00071', 'nama' => 'CONCRETE MIXER'],
            ['kode' => 'CV-00072', 'nama' => 'CONCRETE VIBRATOR'],
            ['kode' => 'CB-00073', 'nama' => 'CONCRETE BREAKER'],
            ['kode' => 'AS-00074', 'nama' => 'AGGREGATE/CHIP SPREADER'],
            ['kode' => 'GM-00075', 'nama' => 'GRAUTING MACHINE'],
            ['kode' => 'CM-00076', 'nama' => 'CONCRETE MOULD'],
            ['kode' => 'PPE-00077', 'nama' => 'PIPE PLANT EQUIPMENT'],
            ['kode' => 'CMT-00078', 'nama' => 'CONCRETE MIXER TANDEM'],
            ['kode' => 'OHM-00079', 'nama' => 'ONION HEAD MACHINE'],
            ['kode' => 'PM-00080', 'nama' => 'PAN MIXER'],
            ['kode' => 'AM-00081', 'nama' => 'ASBUTON MIXER'],
            ['kode' => 'PM-00082', 'nama' => 'PADDLE MIXER'],
            ['kode' => 'ABC-00083', 'nama' => 'ASPHALT BUTON CRUSHER'],
            ['kode' => 'RD-00084', 'nama' => 'ROCK DRILL'],
            ['kode' => 'ACEL-00085', 'nama' => 'AGGREGATE & CONCRETE EQUIPMENT LAINNYA'],
            ['kode' => 'L-00086', 'nama' => 'LOADER'],
            ['kode' => 'TLA-00087', 'nama' => 'TRACK LOADER + ATTACHMENT'],
            ['kode' => 'WLA-00088', 'nama' => 'WHEEL LOADER + ATTACHMENT'],
            ['kode' => 'MDL-00089', 'nama' => 'MAIN DECK LOADER'],
            ['kode' => 'CBT-00090', 'nama' => 'CONVEYOR BELT TRUCK'],
            ['kode' => 'HLL-00091', 'nama' => 'HIGH LIFT LOADER'],
            ['kode' => 'BL-00092', 'nama' => 'BACKHOE LOADER'],
            ['kode' => 'LL-00093', 'nama' => 'LOADER LAINNYA'],
            ['kode' => 'AP-00094', 'nama' => 'ALAT PENGANGKAT'],
            ['kode' => 'TC-00095', 'nama' => 'TOWER CRANE'],
            ['kode' => 'TMC-00096', 'nama' => 'TRUCK MOUNTED CRANE'],
            ['kode' => 'TC-00097', 'nama' => 'TRUCK CRANE'],
            ['kode' => 'WC-00098', 'nama' => 'WHEEL CRANE'],
            ['kode' => 'F-00099', 'nama' => 'FORKLIFT'],
            ['kode' => 'FC-00100', 'nama' => 'FORTAL CRANE'],
            ['kode' => 'CC-00101', 'nama' => 'CRAWLER CRANE'],
            ['kode' => 'CC-00102', 'nama' => 'CONTAINER CRANE'],
            ['kode' => 'T-00103', 'nama' => 'TRANSTAINER'],
            ['kode' => 'TCS-00104', 'nama' => 'TRAVELT CONTAINER STACKER'],
            ['kode' => 'TL-00105', 'nama' => 'TOP LOADER'],
            ['kode' => 'RL-00106', 'nama' => 'RAIL LIFTER'],
            ['kode' => 'TMC-00107', 'nama' => 'TRACK MOTOR CAR'],
            ['kode' => 'SPU-00108', 'nama' => 'SALVAGE PESAWAT UDARA'],
            ['kode' => 'HPT-00109', 'nama' => 'HAND PALET TRUCK'],
            ['kode' => 'CS2T-00110', 'nama' => 'CRANE SHOVEL 20 T'],
            ['kode' => 'SWWCS2T-00111', 'nama' => 'SHOP WOOD WORKING CRANE SHOVEL 20 T'],
            ['kode' => 'APL-00112', 'nama' => 'ALAT PENGANGKAT LAINNYA'],
            ['kode' => 'MP-00113', 'nama' => 'MESIN PROSES'],
            ['kode' => 'MPP-00114', 'nama' => 'MESIN PEMBUAT PELLET'],
            ['kode' => 'MPE-00115', 'nama' => 'MESIN PEMBUAT ES'],
            ['kode' => 'MPE-00116', 'nama' => 'MESIN PENGHANCUR ES'],
            ['kode' => 'WTMP-00117', 'nama' => 'WATER TREATMENT (MESIN PROSES)'],
            ['kode' => 'SWT-00118', 'nama' => 'SEA WATER TREATMENT'],
            ['kode' => 'MPD-00119', 'nama' => 'MESIN PENGOLAH DODOL'],
            ['kode' => 'MPL-00120', 'nama' => 'MESIN PROSES LAINNYA'],
            ['kode' => 'ABDL-00121', 'nama' => 'ALAT BESAR DARAT LAINNYA'],
            ['kode' => 'ABA-00122', 'nama' => 'ALAT BESAR APUNG'],
            ['kode' => 'D-00123', 'nama' => 'DREDGER'],
            ['kode' => 'SD-00124', 'nama' => 'SUCTION DREDGER'],
            ['kode' => 'BD-00125', 'nama' => 'BUCKET DREDGER'],
            ['kode' => 'CSD-00126', 'nama' => 'CUTTER SUCTION DREDGER'],
            ['kode' => 'DL-00127', 'nama' => 'DREDGER LAINNYA'],
            ['kode' => 'FE-00128', 'nama' => 'FLOATING EXCAVATOR'],
            ['kode' => 'FEA-00129', 'nama' => 'FLOATING EXCAVATOR + ATTACHMENT'],
            ['kode' => 'FC-00130', 'nama' => 'FLOATING CRANE'],
            ['kode' => 'FP-00131', 'nama' => 'FLOATING PUMP'],
            ['kode' => 'FEL-00132', 'nama' => 'FLOATING EXCAVATOR LAINNYA'],
            ['kode' => 'AD-00133', 'nama' => 'AMPHIBI DREDGER'],
            ['kode' => 'PS-00134', 'nama' => 'PLAIN SUCTION'],
            ['kode' => 'CAD-00135', 'nama' => 'CUTTER (AMPHIBI DREDGER)'],
            ['kode' => 'C/D-00136', 'nama' => 'CLAMSHELL / DRAGLINE'],
            ['kode' => 'ADL-00137', 'nama' => 'AMPHIBI DREDGER LAINNYA'],
            ['kode' => 'KT-00138', 'nama' => 'KAPAL TARIK'],
            ['kode' => 'KTL-00139', 'nama' => 'KAPAL TARIK LAINNYA'],
            ['kode' => 'MPA-00140', 'nama' => 'MESIN PROSES APUNG'],
            ['kode' => 'WTMPA-00141', 'nama' => 'WATER TREATMENT (MESIN PROSES APUNG)'],
            ['kode' => 'MPAL-00142', 'nama' => 'MESIN PROSES APUNG LAINNYA'],
            ['kode' => 'ABAL-00143', 'nama' => 'ALAT BESAR APUNG LAINNYA'],
            ['kode' => 'AB-00144', 'nama' => 'ALAT BANTU'],
            ['kode' => 'AP-00145', 'nama' => 'ALAT PENARIK'],
            ['kode' => 'APK-00146', 'nama' => 'ALAT PENARIK KAPAL'],
            ['kode' => 'APJ-00147', 'nama' => 'ALAT PENARIK JARING'],
            ['kode' => 'APL-00148', 'nama' => 'ALAT PENARIK LAINNYA'],
            ['kode' => 'F-00149', 'nama' => 'FEEDER'],
            ['kode' => 'E/-00150', 'nama' => 'ELEVATOR /LIFT'],
            ['kode' => 'BCF-00151', 'nama' => 'BELT CONVEYOR (FEEDER)'],
            ['kode' => 'SCF-00152', 'nama' => 'SCREW CONVEYOR (FEEDER)'],
            ['kode' => 'E-00153', 'nama' => 'ESCALATOR'],
            ['kode' => 'G-00154', 'nama' => 'GANDOLA'],
            ['kode' => 'EF-00155', 'nama' => 'ELEVATOR (FEEDER)'],
            ['kode' => 'G-00156', 'nama' => 'GANGWAY'],
            ['kode' => 'FLAB-00157', 'nama' => 'FEEDER LAINNYA (ALAT BESAR)'],
            ['kode' => 'C-00158', 'nama' => 'COMPRESSOR'],
            ['kode' => 'TC-00159', 'nama' => 'TRANSPORTABLE COMPRESSOR'],
            ['kode' => 'PC-00160', 'nama' => 'PORTABLE COMPRESSOR'],
            ['kode' => 'SC-00161', 'nama' => 'STATIONARY COMPRESSOR'],
            ['kode' => 'AC-00162', 'nama' => 'AIR COMPRESOR'],
            ['kode' => 'CPT2G-00163', 'nama' => 'COMPRESSOR PNEUMATIC TOOL 25 GMP'],
            ['kode' => 'CL-00164', 'nama' => 'COMPRESSOR LAINNYA'],
            ['kode' => 'EGS-00165', 'nama' => 'ELECTRIC GENERATING SET'],
            ['kode' => 'TGS-00166', 'nama' => 'TRANSPORTABLE GENERATING SET'],
            ['kode' => 'PGS-00167', 'nama' => 'PORTABLE GENERATING SET'],
            ['kode' => 'SGS-00168', 'nama' => 'STATIONARY GENERATING SET'],
            ['kode' => 'DE-00169', 'nama' => 'DYNAMO ELECTRIC'],
            ['kode' => 'EGSL-00170', 'nama' => 'ELECTRIC GENERATING SET LAINNYA'],
            ['kode' => 'P-00171', 'nama' => 'POMPA'],
            ['kode' => 'TWP-00172', 'nama' => 'TRANSPORTABLE WATER PUMP'],
            ['kode' => 'PWP-00173', 'nama' => 'PORTABLE WATER PUMP'],
            ['kode' => 'SWP-00174', 'nama' => 'STATIONARY WATER PUMP'],
            ['kode' => 'PL-00175', 'nama' => 'POMPA LUMPUR'],
            ['kode' => 'SP-00176', 'nama' => 'SUMERSIBLE PUMP'],
            ['kode' => 'PT-00177', 'nama' => 'POMPA TANGAN'],
            ['kode' => 'PA-00178', 'nama' => 'POMPA ANGIN'],
            ['kode' => 'PBS-00179', 'nama' => 'POMPA BENSIN/MINYAK STATIONERY'],
            ['kode' => 'PBT-00180', 'nama' => 'POMPA BENSIN/MINYAK TRANSPORTABLE'],
            ['kode' => 'PA-00181', 'nama' => 'POMPA AIR'],
            ['kode' => 'WD-00182', 'nama' => 'WATER DISTRIBUTOR'],
            ['kode' => 'WP-00183', 'nama' => 'WATER PURIFICATION'],
            ['kode' => 'PL-00184', 'nama' => 'POMPA LAINNYA'],
            ['kode' => 'MB-00185', 'nama' => 'MESIN BOR'],
            ['kode' => 'MBB-00186', 'nama' => 'MESIN BOR BATU'],
            ['kode' => 'MBT-00187', 'nama' => 'MESIN BOR TANAH'],
            ['kode' => 'MBB-00188', 'nama' => 'MESIN BOR BETON'],
            ['kode' => 'MBL-00189', 'nama' => 'MESIN BOR LAINNYA'],
            ['kode' => 'UPL-00190', 'nama' => 'UNIT PEMELIHARAAN LAPANGAN'],
            ['kode' => 'MW-00191', 'nama' => 'MOBIL WORKSHOP'],
            ['kode' => 'SC-00192', 'nama' => 'SERVICE CAR'],
            ['kode' => 'FW-00193', 'nama' => 'FLOATING WORKSHOP'],
            ['kode' => 'RMT-00194', 'nama' => 'ROAD MAINTENANCE TRUCK'],
            ['kode' => 'ST-00195', 'nama' => 'SWEEPER TRUCK'],
            ['kode' => 'WC-00196', 'nama' => 'WRECK CAR'],
            ['kode' => 'LDUPL-00197', 'nama' => 'LEAK DETECTOR (UNIT PEMELIHARAAN LAPANGAN)'],
            ['kode' => 'PL-00198', 'nama' => 'PIPE LOCATOR'],
            ['kode' => 'ML-00199', 'nama' => 'METAL LOCATOR'],
            ['kode' => 'MD-00200', 'nama' => 'MESIN DIESEL'],
            ['kode' => 'KH-00201', 'nama' => 'KETLE HEATING'],
            ['kode' => 'SPO-00202', 'nama' => 'SWEEPER PENGHISAP OLI'],
            ['kode' => 'FT-00203', 'nama' => 'FUEL TANK'],
            ['kode' => 'GC-00204', 'nama' => 'GRASS COLECTOR'],
            ['kode' => 'MPAD-00205', 'nama' => 'MESIN PEMOTONG ASPAL (DRAGING)'],
            ['kode' => 'SR-00206', 'nama' => 'SWEEPER ROTARY'],
            ['kode' => 'EVT-00207', 'nama' => 'EARTH VAGER TRUCK'],
            ['kode' => 'S-00208', 'nama' => 'SCRAPPER'],
            ['kode' => 'R-00209', 'nama' => 'ROSTER'],
            ['kode' => 'STE-00210', 'nama' => 'SHOP TRUCK EQUIPMENT'],
            ['kode' => 'UPLL-00211', 'nama' => 'UNIT PEMELIHARAAN LAPANGAN LAINNYA'],
            ['kode' => 'APAK-00212', 'nama' => 'ALAT PENGOLAHAN AIR KOTOR'],
            ['kode' => 'UPAK-00213', 'nama' => 'UNIT PENGOLAHAN AIR KOTOR'],
            ['kode' => 'APAKL-00214', 'nama' => 'ALAT PENGOLAHAN AIR KOTOR LAINNYA'],
            ['kode' => 'PUAPG-00215', 'nama' => 'PEMBANGKIT UAP AIR PANAS/STEAM GENERATOR'],
            ['kode' => 'UPUAP-00216', 'nama' => 'UNIT PEMBANGKIT UAP AIR PANAS'],
            ['kode' => 'PUAPGL-00217', 'nama' => 'PEMBANGKIT UAP AIR PANAS/STEAM GENERATOR LAINNYA'],
            ['kode' => 'PKH-00218', 'nama' => 'PERALATAN KEBAKARAN HUTAN'],
            ['kode' => 'BPPPB-00219', 'nama' => 'BACKPACK PUMP (POMPA PUNGGUNG BESAR)'],
            ['kode' => 'FFPPPK-00220', 'nama' => 'FLOATING FIRE PUMP (POMPA PUNGGUNG KECIL)'],
            ['kode' => 'PP-00221', 'nama' => 'POMPA PORTABLE'],
            ['kode' => 'JS-00222', 'nama' => 'JET SHOOTER'],
            ['kode' => 'GP-00223', 'nama' => 'GOLOK PEMADAM'],
            ['kode' => 'BSSP-00224', 'nama' => 'BLADE SHOVEL (SEKOP PEMADAM)'],
            ['kode' => 'S-00225', 'nama' => 'SUMBUT'],
            ['kode' => 'VB-00226', 'nama' => 'VELD BED'],
            ['kode' => 'RP-00227', 'nama' => 'RANSEL PEMADAM'],
            ['kode' => 'FBH-00228', 'nama' => 'FULL BODY HARNESS'],
            ['kode' => 'SH-00229', 'nama' => 'SIT HARNESS'],
            ['kode' => 'F-00230', 'nama' => 'FIGURE'],
            ['kode' => 'A-00231', 'nama' => 'ASCENDER'],
            ['kode' => 'SL-00232', 'nama' => 'SCROLL LOCK'],
            ['kode' => 'PR-00233', 'nama' => 'PERLENGKAPAN RESCUE'],
            ['kode' => 'ASH-00234', 'nama' => 'AUTOMATIC SNAP HOOK'],
            ['kode' => 'TT-00235', 'nama' => 'TANGGA TALI'],
            ['kode' => 'NTA-00236', 'nama' => 'NOZEL TABIR ALUMUNIUM'],
            ['kode' => 'NKP-00237', 'nama' => 'NOZEL KUNINGAN PERNEKEL'],
            ['kode' => 'SA-00238', 'nama' => 'SELANG AIR'],
            ['kode' => 'BAT1K-00239', 'nama' => 'BREATHING APARATUS (TABUNG 10 KG)'],
            ['kode' => 'GP-00240', 'nama' => 'GEPYOK PEMADAM'],
            ['kode' => 'FRGT-00241', 'nama' => 'FIRE RAKE (GARU TAJAM)'],
            ['kode' => 'PAKDF-00242', 'nama' => 'PULASKI AXE (KAPAK DUA FUNGSI)'],
            ['kode' => 'FTGPC-00243', 'nama' => 'FIRE TOOL (GARU PACUL/ CANGKUL)'],
            ['kode' => 'SS-00244', 'nama' => 'SABIT SEMAK'],
            ['kode' => 'FPA-00245', 'nama' => 'FLAPPER (PEMUKUL API)'],
            ['kode' => 'DTOST-00246', 'nama' => 'DRIP TORCH (OBOR SULUT TETES)'],
            ['kode' => 'FKB-00247', 'nama' => 'FILES (KIKIR BAJA)'],
            ['kode' => 'KMLTP-00248', 'nama' => 'KACA MATA (LENSA TAHAN PANAS)'],
            ['kode' => 'KR-00249', 'nama' => 'KOPEL REM'],
            ['kode' => 'F-00250', 'nama' => 'FELPES'],
            ['kode' => 'KA-00251', 'nama' => 'KANTONG AIR'],
            ['kode' => 'BP-00252', 'nama' => 'BATANG POMPA'],
            ['kode' => 'PKHL-00253', 'nama' => 'PERALATAN KEBAKARAN HUTAN LAINNYA'],
            ['kode' => 'PS-00254', 'nama' => 'PERALATAN SELAM'],
            ['kode' => 'TTS-00255', 'nama' => 'TANKS (TABUNG SELAM)'],
            ['kode' => 'SK-00256', 'nama' => 'SEPATU KARANG'],
            ['kode' => 'KPS-00257', 'nama' => 'KNIVES (PISAU SELAM)'],
            ['kode' => 'DLSS-00258', 'nama' => 'DIVE LIGHTS (SENTER SELAM)'],
            ['kode' => 'RI-00259', 'nama' => 'REGULATOR INSTRUMENTS'],
            ['kode' => 'BCDB-00260', 'nama' => 'BOUYANCY COMPENSATOR DEVICE (BCD)'],
            ['kode' => 'BSP-00261', 'nama' => 'BELT (SABUK PEMBERAT)'],
            ['kode' => 'WP-00262', 'nama' => 'WEIGHT (PEMBERAT)'],
            ['kode' => 'DGSTS-00263', 'nama' => 'DIVING GLOVES (SARUNG TANGAN SELAM)'],
            ['kode' => 'KS-00264', 'nama' => 'KOMPRESOR SELAM'],
            ['kode' => 'PLJ-00265', 'nama' => 'PELAMPUNG LIFE JACKET'],
            ['kode' => 'PSL-00266', 'nama' => 'PERALATAN SELAM LAINNYA'],
            ['kode' => 'PSM-00267', 'nama' => 'PERALATAN SAR MOUNTENERING'],
            ['kode' => 'TKS-00268', 'nama' => 'TALI KAMANTEL STATIC'],
            ['kode' => 'TKD-00269', 'nama' => 'TALI KAMANTEL DINAMIC'],
            ['kode' => 'RP-00270', 'nama' => 'RAINCOAT (PONCO)'],
            ['kode' => 'SH-00271', 'nama' => 'SEAT HARNESS'],
            ['kode' => 'P-00272', 'nama' => 'PRUSIK'],
            ['kode' => 'J-00273', 'nama' => 'JUMMAR'],
            ['kode' => 'P-00274', 'nama' => 'PULLEY'],
            ['kode' => 'DFOE-00275', 'nama' => 'DESCENDER FIGURE OG EIGHT'],
            ['kode' => 'CNS-00276', 'nama' => 'CARABINER NON SCREW'],
            ['kode' => 'W-00277', 'nama' => 'WEBBING'],
            ['kode' => 'TL-00278', 'nama' => 'TANDU LIPAT'],
            ['kode' => 'PSML-00279', 'nama' => 'PERALATAN SAR MOUNTENERING LAINNYA'],
            ['kode' => 'ABL-00280', 'nama' => 'ALAT BANTU LAINNYA'],
            ['kode' => 'AA-00281', 'nama' => 'ALAT ANGKUTAN'],
            ['kode' => 'AADB-00282', 'nama' => 'ALAT ANGKUTAN DARAT BERMOTOR'],
            ['kode' => 'KDBP-00283', 'nama' => 'KENDARAAN DINAS BERMOTOR PERORANGAN'],
            ['kode' => 'S-00284', 'nama' => 'SEDAN'],
            ['kode' => 'J-00285', 'nama' => 'JEEP'],
            ['kode' => 'SW-00286', 'nama' => 'STATION WAGON'],
            ['kode' => 'KDBPL-00287', 'nama' => 'KENDARAAN DINAS BERMOTOR PERORANGAN LAINNYA'],
            ['kode' => 'KBP-00288', 'nama' => 'KENDARAAN BERMOTOR PENUMPANG'],
            ['kode' => 'BP3OK-00289', 'nama' => 'BUS ( PENUMPANG 30 ORANG KEATAS )'],
            ['kode' => 'MBP1S2O-00290', 'nama' => 'MICRO BUS ( PENUMPANG 15 S/D 29 ORANG )'],
            ['kode' => 'MBP1OK-00291', 'nama' => 'MINI BUS ( PENUMPANG 14 ORANG KEBAWAH )'],
            ['kode' => 'KLB-00292', 'nama' => 'KENDARAAN LAPIS BAJA'],
            ['kode' => 'KBPL-00293', 'nama' => 'KENDARAAN BERMOTOR PENUMPANG LAINNYA'],
            ['kode' => 'KBAB-00294', 'nama' => 'KENDARAAN BERMOTOR ANGKUTAN BARANG'],
            ['kode' => 'TA-00295', 'nama' => 'TRUCK + ATTACHMENT'],
            ['kode' => 'PU-00296', 'nama' => 'PICK UP'],
            ['kode' => 'Y-00297', 'nama' => 'YEENGLER/TRAILER'],
            ['kode' => 'ST-00298', 'nama' => 'SEMI TRAILER'],
            ['kode' => 'TPDT-00299', 'nama' => 'TRUCK PONTON DENGAN TRAILLER'],
            ['kode' => 'D-00300', 'nama' => 'DALHURA'],
            ['kode' => 'KBABL-00301', 'nama' => 'KENDARAAN BERMOTOR ANGKUTAN BARANG LAINNYA'],
            ['kode' => 'KBBD-00302', 'nama' => 'KENDARAAN BERMOTOR BERODA DUA'],
            ['kode' => 'SM-00303', 'nama' => 'SEPEDA MOTOR'],
            ['kode' => 'S-00304', 'nama' => 'SCOOTER'],
            ['kode' => 'SMPK-00305', 'nama' => 'SEPEDA MOTOR PERPUSTAKAAN KELILING'],
            ['kode' => 'SMP-00306', 'nama' => 'SEPEDA MOTOR PATROLI'],
            ['kode' => 'SMP-00307', 'nama' => 'SEPEDA MOTOR PENGAWALAN'],
            ['kode' => 'KBBDL-00308', 'nama' => 'KENDARAAN BERMOTOR BERODA DUA LAINNYA'],
            ['kode' => 'KBK-00309', 'nama' => 'KENDARAAN BERMOTOR KHUSUS'],
            ['kode' => 'MA-00310', 'nama' => 'MOBIL AMBULANCE'],
            ['kode' => 'MJ-00311', 'nama' => 'MOBIL JENAZAH'],
            ['kode' => 'MUPD-00312', 'nama' => 'MOBIL UNIT PENERANGAN DARAT'],
            ['kode' => 'MPK-00313', 'nama' => 'MOBIL PEMADAM KEBAKARAN'],
            ['kode' => 'MT-00314', 'nama' => 'MOBIL TINJA'],
            ['kode' => 'MTA-00315', 'nama' => 'MOBIL TANGKI AIR'],
            ['kode' => 'MUMF-00316', 'nama' => 'MOBIL UNIT MONITORING FREKWENSI'],
            ['kode' => 'MUPK-00317', 'nama' => 'MOBIL UNIT PERPUSTAKAAN KELILING'],
            ['kode' => 'MUVMM-00318', 'nama' => 'MOBIL UNIT VISUAL MINI (MUVIANI)'],
            ['kode' => 'MUSLV-00319', 'nama' => 'MOBIL UNIT SATELITE LINK VAN'],
            ['kode' => 'MUP-00320', 'nama' => 'MOBIL UNIT PANGGUNG'],
            ['kode' => 'MUP-00321', 'nama' => 'MOBIL UNIT PAMERAN'],
            ['kode' => 'OSBCVR-00322', 'nama' => 'OUT SIDE BROAD CAST VAN RADIO'],
            ['kode' => 'OSBCVT-00323', 'nama' => 'OUT SIDE BROAD CAST VAN TELEVISI'],
            ['kode' => 'MUPF-00324', 'nama' => 'MOBIL UNIT PRODUKSI FILM'],
            ['kode' => 'MUPT-00325', 'nama' => 'MOBIL UNIT PRODUKSI TELEVISI'],
            ['kode' => 'MUPC-00326', 'nama' => 'MOBIL UNIT PRODUKSI CINERAMA'],
            ['kode' => 'MUKM-00327', 'nama' => 'MOBIL UNIT KESEHATAN MASYARAKAT'],
            ['kode' => 'MUKH-00328', 'nama' => 'MOBIL UNIT KESEHATAN HEWAN'],
            ['kode' => 'MUT-00329', 'nama' => 'MOBIL UNIT TAHANAN'],
            ['kode' => 'MUPU-00330', 'nama' => 'MOBIL UNIT PENGANGKUT UANG'],
            ['kode' => 'TS-00331', 'nama' => 'TRUCK SAMPAH'],
            ['kode' => 'MTBB-00332', 'nama' => 'MOBIL TANGKI BAHAN BAKAR'],
            ['kode' => 'MUR-00333', 'nama' => 'MOBIL UNIT RONTGEN'],
            ['kode' => 'MURSK-00334', 'nama' => 'MOBIL UNIT REHABILITASI SOSIAL KELILING'],
            ['kode' => 'BT-00335', 'nama' => 'BOMP TRAILER'],
            ['kode' => 'KK-00336', 'nama' => 'KENDARAAN KLINIK'],
            ['kode' => 'MUPLRA-00337', 'nama' => 'MOBIL UNIT PENGANGKUT LIMBAH RADIO AKTIF'],
            ['kode' => 'MTD-00338', 'nama' => 'MOBIL TRANFUSI DARAH'],
            ['kode' => 'KTP-00339', 'nama' => 'KENDARAAN TIM PEMELIHARAAN'],
            ['kode' => 'MPU-00340', 'nama' => 'MOBIL PENARIK (UNIMOG)'],
            ['kode' => 'KS-00341', 'nama' => 'KENDARAAN SATMOBEK/SATMOBENG/SATMOMAS'],
            ['kode' => 'MWS-00342', 'nama' => 'MOBIL WORK SHOP/SERVICES'],
            ['kode' => 'KD-00343', 'nama' => 'KENDARAAN DEREK'],
            ['kode' => 'MUKA-00344', 'nama' => 'MOBIL UNIT KHUSUS ALJIHANDAK'],
            ['kode' => 'AAC-00345', 'nama' => 'AIRCRAFT AIR CONDITIONING'],
            ['kode' => 'KGR-00346', 'nama' => 'KENDARAAN GIRAFLE RADAR'],
            ['kode' => 'MPV-00347', 'nama' => 'MOBIL PERS VAN'],
            ['kode' => 'KUB-00348', 'nama' => 'KENDARAAN UNIT BEDAH'],
            ['kode' => 'MF-00349', 'nama' => 'MOBILE FLOODLIGHT'],
            ['kode' => 'KPT-00350', 'nama' => 'KENDARAAN PENGANGKUT TANK'],
            ['kode' => 'CC-00351', 'nama' => 'CRASH CAR'],
            ['kode' => 'KWC-00352', 'nama' => 'KENDARAAN WATER CANON'],
            ['kode' => 'FV-00353', 'nama' => 'FOAM VEHICLE'],
            ['kode' => 'KT-00354', 'nama' => 'KENDARAAN TOILET'],
            ['kode' => 'RIV-00355', 'nama' => 'RAPID INVENTION VEHICLE'],
            ['kode' => 'KGA-00356', 'nama' => 'KENDARAAN GAS AIRMATA'],
            ['kode' => 'KT-00357', 'nama' => 'KENDARAAN TAKTIS'],
            ['kode' => 'KVAP-00358', 'nama' => 'KENDARAAN VIP (ANTI PELURU)'],
            ['kode' => 'KTP-00359', 'nama' => 'KENDARAAN TANGGA PESAWAT'],
            ['kode' => 'KM-00360', 'nama' => 'KENDARAAN METEO'],
            ['kode' => 'KS-00361', 'nama' => 'KENDARAAN SWEEPER'],
            ['kode' => 'KKS-00362', 'nama' => 'KENDARAAN KAMAR SANDI'],
            ['kode' => 'KJF-00363', 'nama' => 'KENDARAAN JAMMING FREKUENSI'],
            ['kode' => 'KMS-00364', 'nama' => 'KENDARAAN MONITORING SINYAL'],
            ['kode' => 'MDL-00365', 'nama' => 'MOBIL DAPUR LAPANGAN'],
            ['kode' => 'MPB-00366', 'nama' => 'MOBIL PENARIK BARRIER'],
            ['kode' => 'MOP-00367', 'nama' => 'MOBIL OPERASIONAL PJR'],
            ['kode' => 'AUVA-00368', 'nama' => 'AUTOMATIC UNGUIDED VEHICLE (AUGV)'],
            ['kode' => 'RC-00369', 'nama' => 'RESCUE CAR'],
            ['kode' => 'RDLS-00370', 'nama' => 'RAPID DEPLOYMENT LAND SAR'],
            ['kode' => 'RT-00371', 'nama' => 'RESCUE TRUCK'],
            ['kode' => 'MMLP-00372', 'nama' => 'MONILOG (MOBIL LOGISTIK/ PERSONIL)'],
            ['kode' => 'ML-00373', 'nama' => 'MOBIL LATIH'],
            ['kode' => 'RSW-00374', 'nama' => 'RAN SWITCH WAGON'],
            ['kode' => 'RCW-00375', 'nama' => 'RAN CACDRI WAGON'],
            ['kode' => 'RT-00376', 'nama' => 'RAN TRAKTOR'],
            ['kode' => 'RT-00377', 'nama' => 'RAN TANGKI'],
            ['kode' => 'RZA-00378', 'nama' => 'RAN ZAT ASAM'],
            ['kode' => 'RPL-00379', 'nama' => 'RAN PENYAPU LANDASAN'],
            ['kode' => 'RPP-00380', 'nama' => 'RAN PANDU PESAWAT'],
            ['kode' => 'RPP-00381', 'nama' => 'RAN PENARIK PESAWAT'],
            ['kode' => 'RPH-00382', 'nama' => 'RAN PENYAPU HANGGAR'],
            ['kode' => 'RDC-00383', 'nama' => 'RAN DRUG CHUTE'],
            ['kode' => 'RPT-00384', 'nama' => 'RAN PEMBANGKIT TENAGA'],
            ['kode' => 'RCS-00385', 'nama' => 'RAN CRIME SQUID'],
            ['kode' => 'RWC-00386', 'nama' => 'RAN WEAPON CARRIER'],
            ['kode' => 'RL/UC-00387', 'nama' => 'RAN LABORATORIUM / UJI COBA'],
            ['kode' => 'RK-00388', 'nama' => 'RAN KANTIN'],
            ['kode' => 'RP-00389', 'nama' => 'RAN PATROLI'],
            ['kode' => 'RJK-00390', 'nama' => 'RAN JEEP KOMMAB'],
            ['kode' => 'RR-00391', 'nama' => 'RAN RECOVERY'],
            ['kode' => 'RPBP-00392', 'nama' => 'RAN PENGISI BB PESAWAT'],
            ['kode' => 'RW-00393', 'nama' => 'RAN WRECKER'],
            ['kode' => 'RF-00394', 'nama' => 'RAN FORKLIP'],
            ['kode' => 'MP-00395', 'nama' => 'MOBIL PATROLI'],
            ['kode' => 'KA-00396', 'nama' => 'KENDARAAN APC'],
            ['kode' => 'KDV-00397', 'nama' => 'KENDARAAN DARE V'],
            ['kode' => 'KP-00398', 'nama' => 'KENDARAAN/MOBIL PENGAWALAN'],
            ['kode' => 'MI-00399', 'nama' => 'MOBIL IRUP'],
            ['kode' => 'MKP-00400', 'nama' => 'MOBIL KOMLEK POLRI'],
            ['kode' => 'MUT-00401', 'nama' => 'MOBIL UNIT TKP'],
            ['kode' => 'MULL-00402', 'nama' => 'MOBIL UNIT LAKA LANTAS'],
            ['kode' => 'MUI-00403', 'nama' => 'MOBIL UNIT IDENTIFIKASI'],
            ['kode' => 'MUL-00404', 'nama' => 'MOBIL UNIT LABFOR'],
            ['kode' => 'MUPP-00405', 'nama' => 'MOBIL UNIT PENERANGAN POLRI'],
            ['kode' => 'MUD-00406', 'nama' => 'MOBIL UNIT DEREK'],
            ['kode' => 'MUS-00407', 'nama' => 'MOBIL UNIT SATWA'],
            ['kode' => 'RP-00408', 'nama' => 'RANTIS PHH'],
            ['kode' => 'KPPM-00409', 'nama' => 'KENDARAAN POS POLISI MOBILE'],
            ['kode' => 'MUAJ-00410', 'nama' => 'MOBIL UNIT ALSUS JIHANDAK'],
            ['kode' => 'MG-00411', 'nama' => 'MOBIL GOLFCAR'],
            ['kode' => 'RRS-00412', 'nama' => 'RANTIS RESCUE SAMAPTA'],
            ['kode' => 'RSATK-00413', 'nama' => 'RANSUS SATWA ANJING TYPE KECIL'],
            ['kode' => 'RSATS-00414', 'nama' => 'RANSUS SATWA ANJING TYPE SEDANG'],
            ['kode' => 'RSATB-00415', 'nama' => 'RANSUS SATWA ANJING TYPE BESAR'],
            ['kode' => 'RSKTS-00416', 'nama' => 'RANSUS SATWA KUDA TYPE SEDANG'],
            ['kode' => 'RSKTB-00417', 'nama' => 'RANSUS SATWA KUDA TYPE BESAR'],
            ['kode' => 'TK-00418', 'nama' => 'TRAILER KUDA'],
            ['kode' => 'KBKL-00419', 'nama' => 'KENDARAAN BERMOTOR KHUSUS LAINNYA'],
            ['kode' => 'AADBL-00420', 'nama' => 'ALAT ANGKUTAN DARAT BERMOTOR LAINNYA'],
            ['kode' => 'AADTB-00421', 'nama' => 'ALAT ANGKUTAN DARAT TAK BERMOTOR'],
            ['kode' => 'KTBAB-00422', 'nama' => 'KENDARAAN TAK BERMOTOR ANGKUTAN BARANG'],
            ['kode' => 'GT-00423', 'nama' => 'GEROBAK TARIK'],
            ['kode' => 'GD-00424', 'nama' => 'GEROBAK DORONG'],
            ['kode' => 'C-00425', 'nama' => 'CARAVAN'],
            ['kode' => 'LD-00426', 'nama' => 'LORI DORONG'],
            ['kode' => 'T-00427', 'nama' => 'TRAILER'],
            ['kode' => 'CD-00428', 'nama' => 'CONTAINER DOLLY'],
            ['kode' => 'PD-00429', 'nama' => 'PALLET DOLLY'],
            ['kode' => 'BAMC-00430', 'nama' => 'BAGGAGE AND MAIL CART'],
            ['kode' => 'BT-00431', 'nama' => 'BAGGAGE TROLLY'],
            ['kode' => 'MDSS-00432', 'nama' => 'MEJA DORONG SAJI/TROLLEY SAJI'],
            ['kode' => 'RDB-00433', 'nama' => 'RODA DUA BERINSULASI'],
            ['kode' => 'RTGKB-00434', 'nama' => 'RODA TIGA/ GEROBAK KAYUH BERINSULASI'],
            ['kode' => 'KTBABL-00435', 'nama' => 'KENDARAAN TAK BERMOTOR ANGKUTAN BARANG LAINNYA'],
            ['kode' => 'KTBP-00436', 'nama' => 'KENDARAAN TAK BERMOTOR PENUMPANG'],
            ['kode' => 'S-00437', 'nama' => 'SEPEDA'],
            ['kode' => 'KKTBP-00438', 'nama' => 'KUDA (KENDARAAN TAK BERMOTOR PENUMPANG)'],
            ['kode' => 'KTBPL-00439', 'nama' => 'KENDARAAN TAK BERMOTOR PENUMPANG LAINNYA'],
            ['kode' => 'AAKRTB-00440', 'nama' => 'ALAT ANGKUTAN KERETA REL TAK BERMOTOR'],
            ['kode' => 'KP-00441', 'nama' => 'KERETA PENUMPANG'],
            ['kode' => 'KM-00442', 'nama' => 'KERETA MAKAN'],
            ['kode' => 'PC-00443', 'nama' => 'POWER CAR'],
            ['kode' => 'GBT-00444', 'nama' => 'GERBONG BARANG TERTUTUP'],
            ['kode' => 'GBT-00445', 'nama' => 'GERBONG BARANG TERBUKA'],
            ['kode' => 'AAKRTBL-00446', 'nama' => 'ALAT ANGKUTAN KERETA REL TAK BERMOTOR LAINNYA'],
            ['kode' => 'AADTBL-00447', 'nama' => 'ALAT ANGKUTAN DARAT TAK BERMOTOR LAINNYA'],
            ['kode' => 'AAAB-00448', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR'],
            ['kode' => 'AAABUB-00449', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR UNTUK BARANG'],
            ['kode' => 'KMT-00450', 'nama' => 'KAPAL MINYAK (TANKER)'],
            ['kode' => 'TB-00451', 'nama' => 'TONGKANG BERMOTOR'],
            ['kode' => 'TBA-00452', 'nama' => 'TUG BOAT + ATTACHMENT'],
            ['kode' => 'LSTL-00453', 'nama' => 'LANDING SHIP TRANSPORTATION( L.S.T )'],
            ['kode' => 'KCKB-00454', 'nama' => 'KAPAL CARGO (KAPAL BARANG)'],
            ['kode' => 'TA-00455', 'nama' => 'TRUCK AIR'],
            ['kode' => 'AAABUBL-00456', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR UNTUK BARANG LAINNYA'],
            ['kode' => 'AAABUP-00457', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR UNTUK PENUMPANG'],
            ['kode' => 'SB/MT-00458', 'nama' => 'SPEED BOAT / MOTOR TEMPEL'],
            ['kode' => 'MB-00459', 'nama' => 'MOTOR BOAT'],
            ['kode' => 'K-00460', 'nama' => 'KLOTOK'],
            ['kode' => 'F-00461', 'nama' => 'FERRY'],
            ['kode' => 'H-00462', 'nama' => 'HIDROFOIL'],
            ['kode' => 'J-00463', 'nama' => 'JETFOIL'],
            ['kode' => 'LB-00464', 'nama' => 'LONG BOAT'],
            ['kode' => 'KPKP-00465', 'nama' => 'KAPAL PASSANGER (KAPAL PENUMPANG)'],
            ['kode' => 'PK-00466', 'nama' => 'PERAHU KAYU'],
            ['kode' => 'AAABUPL-00467', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR UNTUK PENUMPANG LAINNYA'],
            ['kode' => 'AAABK-00468', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR KHUSUS'],
            ['kode' => 'SB-00469', 'nama' => 'SURVEY BOAT'],
            ['kode' => 'KAP-00470', 'nama' => 'KAPAL ANTI POLUSI'],
            ['kode' => 'KP-00471', 'nama' => 'KAPAL PERAMBUAN'],
            ['kode' => 'OBM-00472', 'nama' => 'OUT BOAT MOTOR'],
            ['kode' => 'KH-00473', 'nama' => 'KAPAL HYDROGRAFI'],
            ['kode' => 'KUPA-00474', 'nama' => 'KAPAL UNIT PENERANGAN AIR'],
            ['kode' => 'KVM-00475', 'nama' => 'KAPAL VISUAL MINI'],
            ['kode' => 'KPI-00476', 'nama' => 'KAPAL PENANGKAP IKAN'],
            ['kode' => 'KPH-00477', 'nama' => 'KAPAL PENGANGKUT HEWAN'],
            ['kode' => 'KPP-00478', 'nama' => 'KAPAL PATROLI PANTAI'],
            ['kode' => 'KMPK-00479', 'nama' => 'KAPAL MOTOR PERPUSTAKAAN KELILING'],
            ['kode' => 'FWS-00480', 'nama' => 'FLOATING WORK SHOP/DOCK'],
            ['kode' => 'MB-00481', 'nama' => 'MORING BOAT/KEPIL'],
            ['kode' => 'SDH-00482', 'nama' => 'SUCTION DREDGER/KERUK HISAP'],
            ['kode' => 'QDB-00483', 'nama' => 'QUTTER DREDGER/KERUK BOR'],
            ['kode' => 'BDT-00484', 'nama' => 'BUCKET DREDGER/KERUK TIMBA'],
            ['kode' => 'CDC-00485', 'nama' => 'CLAMPSHEL DREDGER/KERUK CAKRAM'],
            ['kode' => 'AAAUM-00486', 'nama' => 'ALAT ANGKUTAN APUNG UNTUK MANCING'],
            ['kode' => 'FPAAAAB-00487', 'nama' => 'FLOATING PILE + ATTACHMENT (ALAT ANGKUTAN APUNG BERMOTOR KHUSUS)'],
            ['kode' => 'SMT-00488', 'nama' => 'SEKOCI MOTOR TEMPEL'],
            ['kode' => 'PMT-00489', 'nama' => 'PERAHU MOTOR TEMPEL'],
            ['kode' => 'KO-00490', 'nama' => 'KAPAL OSEANOGRAFI'],
            ['kode' => 'PT-00491', 'nama' => 'PERAHU TRADISIONAL'],
            ['kode' => 'SR-00492', 'nama' => 'SEA RIDER'],
            ['kode' => 'HC-00493', 'nama' => 'HOVER CRAFT'],
            ['kode' => 'KPI-00494', 'nama' => 'KAPAL PENGANGKUT IKAN'],
            ['kode' => 'KPI-00495', 'nama' => 'KAPAL PENGOLAH IKAN'],
            ['kode' => 'KPEP-00496', 'nama' => 'KAPAL PENELITIAN/ EKSPLORASI PERIKANAN'],
            ['kode' => 'KPOPI-00497', 'nama' => 'KAPAL PENDUKUNG OPERASI PENANGKAPAN IKAN'],
            ['kode' => 'KPOPI-00498', 'nama' => 'KAPAL PENDUKUNG OPERASI PEMBUDIDAYAAN IKAN'],
            ['kode' => 'KPP-00499', 'nama' => 'KAPAL PENGAWAS PERIKANAN'],
            ['kode' => 'PI3O-00500', 'nama' => 'PERAHU INTAI 3 ORANG'],
            ['kode' => 'PS1O-00501', 'nama' => 'PERAHU SERBU 15 ORANG'],
            ['kode' => 'KPP-00502', 'nama' => 'KAPAL PATROLI POLISI'],
            ['kode' => 'JS-00503', 'nama' => 'JET SKY'],
            ['kode' => 'AAABKL-00504', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR KHUSUS LAINNYA'],
            ['kode' => 'AAABL-00505', 'nama' => 'ALAT ANGKUTAN APUNG BERMOTOR LAINNYA'],
            ['kode' => 'AAATB-00506', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR'],
            ['kode' => 'AAATBUB-00507', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR UNTUK BARANG'],
            ['kode' => 'T-00508', 'nama' => 'TONGKANG'],
            ['kode' => 'PB-00509', 'nama' => 'PERAHU BARANG'],
            ['kode' => 'AAATBUBL-00510', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR UNTUK BARANG LAINNYA'],
            ['kode' => 'AAATBUP-00511', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR UNTUK PENUMPANG'],
            ['kode' => 'PP-00512', 'nama' => 'PERAHU PENUMPANG'],
            ['kode' => 'PP-00513', 'nama' => 'PERAHU PENYEBERANGAN'],
            ['kode' => 'AAATBUPL-00514', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR UNTUK PENUMPANG LAINNYA'],
            ['kode' => 'AAATBK-00515', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR KHUSUS'],
            ['kode' => 'P-00516', 'nama' => 'PONTON'],
            ['kode' => 'PKAAATBK-00517', 'nama' => 'PERAHU KARET (ALAT ANGKUTAN APUNG TAK BERMOTOR KHUSUS)'],
            ['kode' => 'PR-00518', 'nama' => 'PONTON RUMAH'],
            ['kode' => 'FP-00519', 'nama' => 'FLOATING PLATFORM/RAKIT'],
            ['kode' => 'AAATBKL-00520', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR KHUSUS LAINNYA'],
            ['kode' => 'AAATBL-00521', 'nama' => 'ALAT ANGKUTAN APUNG TAK BERMOTOR LAINNYA'],
            ['kode' => 'ABDAU-00522', 'nama' => 'ALAT BENGKEL DAN ALAT UKUR'],
            ['kode' => 'ABB-00523', 'nama' => 'ALAT BENGKEL BERMESIN'],
            ['kode' => 'PKLTPP-00524', 'nama' => 'PERKAKAS KONSTRUKSI LOGAM TERPASANG PADA PONDASI'],
            ['kode' => 'MB-00525', 'nama' => 'MESIN BUBUT'],
            ['kode' => 'MF-00526', 'nama' => 'MESIN FRAIS'],
            ['kode' => 'MKPKLTPP-00527', 'nama' => 'MESIN KETAM (PERKAKAS KONSTRUKSI LOGAM TERPASANG PADA PONDASI)'],
            ['kode' => 'MPHP-00528', 'nama' => 'MESIN PRESS HIDROLIK & PUNCH'],
            ['kode' => 'MGL-00529', 'nama' => 'MESIN GERGAJI LOGAM'],
            ['kode' => 'MG-00530', 'nama' => 'MESIN GERINDA'],
            ['kode' => 'MR-00531', 'nama' => 'MESIN ROL'],
            ['kode' => 'MBC-00532', 'nama' => 'MESIN BOR CYLINDER'],
            ['kode' => 'MS-00533', 'nama' => 'MESIN SKRUP'],
            ['kode' => 'MM-00534', 'nama' => 'MESIN MEILING'],
            ['kode' => 'MP-00535', 'nama' => 'MESIN PUREL'],
            ['kode' => 'MP-00536', 'nama' => 'MESIN PERAPEN'],
            ['kode' => 'MSK-00537', 'nama' => 'MESIN SIKAT KULIT'],
            ['kode' => 'MPK-00538', 'nama' => 'MESIN PEMOTONG KULIT'],
            ['kode' => 'MJK-00539', 'nama' => 'MESIN JAHIT KULIT'],
            ['kode' => 'MPK-00540', 'nama' => 'MESIN PENGEPRES KULIT'],
            ['kode' => 'MK-00541', 'nama' => 'MESIN KOMPRESOR'],
            ['kode' => 'MLL-00542', 'nama' => 'MESIN LAS LISTRIK'],
            ['kode' => 'MDK-00543', 'nama' => 'MESIN DYNAMO KRON'],
            ['kode' => 'MSBK-00544', 'nama' => 'MESIN SIKAT BESI KRON'],
            ['kode' => 'MPF-00545', 'nama' => 'MESIN PEMOTONG FIBERGLAS/POLIYSTER'],
            ['kode' => 'MGL-00546', 'nama' => 'MESIN GULUNG LISTRIK'],
            ['kode' => 'MPPKLTPP-00547', 'nama' => 'MESIN PELUBANG (PERKAKAS KONSTRUKSI LOGAM TERPASANG PADA PONDASI)'],
            ['kode' => 'MPP-00548', 'nama' => 'MESIN PENEKUK/LIPAT PLAT'],
            ['kode' => 'MGP-00549', 'nama' => 'MESIN GUNTING PLAT'],
            ['kode' => 'MPU-00550', 'nama' => 'MESIN PEMBENGKOK UNI'],
            ['kode' => 'MAP-00551', 'nama' => 'MESIN AMPLAS PLAT'],
            ['kode' => 'MPP-00552', 'nama' => 'MESIN PEMOTONG PLAT'],
            ['kode' => 'MTA-00553', 'nama' => 'MESIN TRANSMISSION AUTOMOTIVE'],
            ['kode' => 'MPL-00554', 'nama' => 'MESIN PEMBENGKOK LOGAM'],
            ['kode' => 'MCG-00555', 'nama' => 'MESIN CRYSTAL GROWING'],
            ['kode' => 'MLC-00556', 'nama' => 'MESIN LASER CUTTING'],
            ['kode' => 'MLW-00557', 'nama' => 'MESIN LASER WELDING'],
            ['kode' => 'MLP-00558', 'nama' => 'MESIN LIPAT PLAT'],
            ['kode' => 'MB-00559', 'nama' => 'MESIN BRIKET'],
            ['kode' => 'UGSV-00560', 'nama' => 'UNIV. GRINDER SETING VALVE'],
            ['kode' => 'UGVR-00561', 'nama' => 'UNIV. GRINDER VALVE REPAIR'],
            ['kode' => 'MS-00562', 'nama' => 'MESIN SERUT'],
            ['kode' => 'MPK-00563', 'nama' => 'MESIN PROFILE KAYU'],
            ['kode' => 'PKLTPPL-00564', 'nama' => 'PERKAKAS KONSTRUKSI LOGAM TERPASANG PADA PONDASI LAINNYA'],
            ['kode' => 'PKLYTB-00565', 'nama' => 'PERKAKAS KONSTRUKSI LOGAM YANG TRANSPORTABLE (BERPINDAH)'],
            ['kode' => 'MGT-00566', 'nama' => 'MESIN GERINDA TANGAN'],
            ['kode' => 'MBT-00567', 'nama' => 'MESIN BOR TANGAN'],
            ['kode' => 'MC-00568', 'nama' => 'MESIN CYLINDER'],
            ['kode' => 'RM-00569', 'nama' => 'RIVETING MACHINE'],
            ['kode' => 'MGM-00570', 'nama' => 'MESIN GULUNG MANUAL'],
            ['kode' => 'MAT-00571', 'nama' => 'MESIN AMPELAS TANGAN'],
            ['kode' => 'MARK-00572', 'nama' => 'MESIN AMPELAS ROL KECIL'],
            ['kode' => 'MGB-00573', 'nama' => 'MESIN GERGAJI BESI'],
            ['kode' => 'PKLYTBL-00574', 'nama' => 'PERKAKAS KONSTRUKSI LOGAM YANG TRANSPORTABLE (BERPINDAH) LAINNYA'],
            ['kode' => 'PBL-00575', 'nama' => 'PERKAKAS BENGKEL LISTRIK'],
            ['kode' => 'BC-00576', 'nama' => 'BATTERY CHARGE'],
            ['kode' => 'W-00577', 'nama' => 'WINDER'],
            ['kode' => 'T-00578', 'nama' => 'TRANSFORMATOR'],
            ['kode' => 'SL-00579', 'nama' => 'SOLDER LISTRIK'],
            ['kode' => 'STL-00580', 'nama' => 'SEDOTAN TIMAH LISTRIK'],
            ['kode' => 'ED-00581', 'nama' => 'ELECTRICAL DISCHARGE'],
            ['kode' => 'VMC-00582', 'nama' => 'VERTICAL MACHINING CENTRE'],
            ['kode' => 'CM-00583', 'nama' => 'COPY MILLING'],
            ['kode' => 'SGP-00584', 'nama' => 'SURFACE GRINDING PROTH'],
            ['kode' => 'CGY-00585', 'nama' => 'CYDRICAL GRINDER YAM'],
            ['kode' => 'CDC-00586', 'nama' => 'CAPACITY DIE CASTING'],
            ['kode' => 'HCM-00587', 'nama' => 'HMC CINTINATI MILACRON'],
            ['kode' => 'ECRE-00588', 'nama' => 'ENGINE CYLINDER RESEARCH ENGINE'],
            ['kode' => 'VS-00589', 'nama' => 'VALVE SENSOR'],
            ['kode' => 'CMM-00590', 'nama' => 'COORDINATE MEASURING MACHINES'],
            ['kode' => 'ECS-00591', 'nama' => 'ENGINE COOLING SYSTEM'],
            ['kode' => 'OMP-00592', 'nama' => 'OUTLET MANIFODLD PRESSURE'],
            ['kode' => 'IOW-00593', 'nama' => 'IMPULSE ORBITAL WELDER'],
            ['kode' => 'AD-00594', 'nama' => 'AVL DIGAS'],
            ['kode' => 'EWR-00595', 'nama' => 'ELECTRIC WIRE ROPE'],
            ['kode' => 'SPG-00596', 'nama' => 'STEAM PRESSURE GAUGE'],
            ['kode' => 'SV-00597', 'nama' => 'SAVETUY VALVE'],
            ['kode' => 'TS-00598', 'nama' => 'TRESHER STATIS'],
            ['kode' => 'V-00599', 'nama' => 'VARIAC'],
            ['kode' => 'MPBL-00600', 'nama' => 'MIXER (PERKAKAS BENGKEL LISTRIK)'],
            ['kode' => 'SM-00601', 'nama' => 'STEPPING MOTOR'],
            ['kode' => 'CPT-00602', 'nama' => 'CYLINDER PRESSURE TRANDUCER'],
            ['kode' => 'ESSP-00603', 'nama' => 'ENGINE SIMULATION SOFTWARE PACKAGE'],
            ['kode' => 'AGA-00604', 'nama' => 'AXHAUST GAS ANALIZER'],
            ['kode' => 'CS-00605', 'nama' => 'CIRCULAR SAW'],
            ['kode' => 'TL-00606', 'nama' => 'TESTER LISTRIK/TELEPON/INTERNET'],
            ['kode' => 'PBLLABB-00607', 'nama' => 'PERKAKAS BENGKEL LISTRIK LAINNYA (ALAT BENGKEL BERMESIN)'],
            ['kode' => 'PBS-00608', 'nama' => 'PERKAKAS BENGKEL SERVICE'],
            ['kode' => 'AL-00609', 'nama' => 'AUTO LIFT'],
            ['kode' => 'CW-00610', 'nama' => 'CAR WASHER'],
            ['kode' => 'SC-00611', 'nama' => 'STEAM CLEANER'],
            ['kode' => 'LE-00612', 'nama' => 'LUBRIACATING EQUIPMENT'],
            ['kode' => 'MS-00613', 'nama' => 'MESIN SPOORING'],
            ['kode' => 'MB-00614', 'nama' => 'MESIN BALANCER'],
            ['kode' => 'BDLPT-00615', 'nama' => 'BRAKE DRUM LATHE/MESIN PERATA TROMOL'],
            ['kode' => 'PLSP-00616', 'nama' => 'PENGASAH LUBANG STANG PISTON'],
            ['kode' => 'LSPBS-00617', 'nama' => 'LUBRICATING SET (PERKAKAS BENGKEL SERVICE)'],
            ['kode' => 'AFR-00618', 'nama' => 'AIR FILTER REGULATOR'],
            ['kode' => 'DCDC-00619', 'nama' => 'DIAMOND CARE DRILL CARE'],
            ['kode' => 'AMC-00620', 'nama' => 'AC MOTOR CONTROL'],
            ['kode' => 'PBSLABB-00621', 'nama' => 'PERKAKAS BENGKEL SERVICE LAINNYA (ALAT BENGKEL BERMESIN)'],
            ['kode' => 'PPB-00622', 'nama' => 'PERKAKAS PENGANGKAT BERMESIN'],
            ['kode' => 'OC-00623', 'nama' => 'OVERHEAD CRANE'],
            ['kode' => 'H-00624', 'nama' => 'HOIST'],
            ['kode' => 'W-00625', 'nama' => 'WINCH/LIR'],
            ['kode' => 'PPBL-00626', 'nama' => 'PERKAKAS PENGANGKAT BERMESIN LAINNYA'],
            ['kode' => 'PBK-00627', 'nama' => 'PERKAKAS BENGKEL KAYU'],
            ['kode' => 'MG-00628', 'nama' => 'MESIN GERGAJI'],
            ['kode' => 'MKPBK-00629', 'nama' => 'MESIN KETAM (PERKAKAS BENGKEL KAYU)'],
            ['kode' => 'MBK-00630', 'nama' => 'MESIN BOR KAYU'],
            ['kode' => 'MP-00631', 'nama' => 'MESIN PENGHALUS'],
            ['kode' => 'TLOM3-00632', 'nama' => 'TATAH LISTRIK OSCAR MK 361'],
            ['kode' => 'PLM-00633', 'nama' => 'PASAH LISTRIK MKC'],
            ['kode' => 'PLM-00634', 'nama' => 'PROFILE LISTRIK MKC'],
            ['kode' => 'GD-00635', 'nama' => 'GRENDO DUDUK'],
            ['kode' => 'GBA-00636', 'nama' => 'GERGAJI BENGKOK ATS'],
            ['kode' => 'ALG-00637', 'nama' => 'AMPLAS LISTRIK GMT'],
            ['kode' => 'GCS-00638', 'nama' => 'GERGAJI CHAIN SAW'],
            ['kode' => 'TS1E-00639', 'nama' => 'TABLE SAW 10 EASTCO'],
            ['kode' => 'PBKL-00640', 'nama' => 'PERKAKAS BENGKEL KAYU LAINNYA'],
            ['kode' => 'PBK-00641', 'nama' => 'PERKAKAS BENGKEL KHUSUS'],
            ['kode' => 'MJT-00642', 'nama' => 'MESIN JAHIT TERPAL'],
            ['kode' => 'PVB-00643', 'nama' => 'PERKAKAS VULKANISIR BAN'],
            ['kode' => 'PBB-00644', 'nama' => 'PERKAKAS BONGKAR/PASANG BAN'],
            ['kode' => 'MTT-00645', 'nama' => 'MESIN TENUN TEKSTIL'],
            ['kode' => 'MCPBK-00646', 'nama' => 'MESIN CELUP (PERKAKAS BENGKEL KHUSUS)'],
            ['kode' => 'PB-00647', 'nama' => 'PEMASANG BARU'],
            ['kode' => 'MTJ-00648', 'nama' => 'MESIN TENUN JAHIT'],
            ['kode' => 'PBKL-00649', 'nama' => 'PERKAKAS BENGKEL KHUSUS LAINNYA'],
            ['kode' => 'PL-00650', 'nama' => 'PERALATAN LAS'],
            ['kode' => 'PLL-00651', 'nama' => 'PERALATAN LAS LISTRIK'],
            ['kode' => 'PLK-00652', 'nama' => 'PERALATAN LAS KARBIT'],
            ['kode' => 'PLG-00653', 'nama' => 'PERALATAN LAS GAS'],
            ['kode' => 'PLL-00654', 'nama' => 'PERALATAN LAS LAINNYA'],
            ['kode' => 'ABBL-00655', 'nama' => 'ALAT BENGKEL BERMESIN LAINNYA'],
            ['kode' => 'ABTB-00656', 'nama' => 'ALAT BENGKEL TAK BERMESIN'],
            ['kode' => 'PBKL-00657', 'nama' => 'PERKAKAS BENGKEL KONSTRUKSI LOGAM'],
            ['kode' => 'PDT-00658', 'nama' => 'PERKAKAS DAPUR TEMPA'],
            ['kode' => 'PBK-00659', 'nama' => 'PERKAKAS BANGKU KERJA'],
            ['kode' => 'PP-00660', 'nama' => 'PERKAKAS PENGUKUR'],
            ['kode' => 'PPL-00661', 'nama' => 'PERKAKAS PENGECORAN LOGAM'],
            ['kode' => 'ROL-00662', 'nama' => 'R O L'],
            ['kode' => 'PPP-00663', 'nama' => 'PERKAKAS PEMOTONG PLAT'],
            ['kode' => 'PPH-00664', 'nama' => 'PERKAKAS PRESS HIDROLIK'],
            ['kode' => 'PPKS-00665', 'nama' => 'PERKAKAS PEMOTONG KABEL SLING'],
            ['kode' => 'PPK-00666', 'nama' => 'PERKAKAS PENGECATAN KENDARAAN'],
            ['kode' => 'PBKLL-00667', 'nama' => 'PERKAKAS BENGKEL KONSTRUKSI LOGAM LAINNYA'],
            ['kode' => 'ADO-00668', 'nama' => 'ARMATURE DRYING OVEN'],
            ['kode' => 'MU-00669', 'nama' => 'MICA UNDERCUTTER'],
            ['kode' => 'CTT-00670', 'nama' => 'COMMUTATOR TURNING TOOL'],
            ['kode' => 'AC-00671', 'nama' => 'ARMATURE CROWLER'],
            ['kode' => 'SSSG-00672', 'nama' => 'SOLID STATE SOLDERING GUN'],
            ['kode' => 'PBLLABTB-00673', 'nama' => 'PERKAKAS BENGKEL LISTRIK LAINNYA (ALAT BENGKEL TAK BERMESIN)'],
            ['kode' => 'PBM-00674', 'nama' => 'PERLENGKAPAN BENGKEL MEKANIK'],
            ['kode' => 'JSH-00675', 'nama' => 'JEMBATAN SERVICE HIDROLIK'],
            ['kode' => 'PBSLABTB-00676', 'nama' => 'PERKAKAS BENGKEL SERVICE LAINNYA (ALAT BENGKEL TAK BERMESIN)'],
            ['kode' => 'PP-00677', 'nama' => 'PERKAKAS PENGANGKAT'],
            ['kode' => 'DM-00678', 'nama' => 'DONGKRAK MEKANIK'],
            ['kode' => 'DH-00679', 'nama' => 'DONGKRAK HIDROLIK'],
            ['kode' => 'TAKEL-00680', 'nama' => 'T A K E L'],
            ['kode' => 'GANTRY-00681', 'nama' => 'G A N T R Y'],
            ['kode' => 'TRIPOD-00682', 'nama' => 'T R I P O D'],
            ['kode' => 'FC-00683', 'nama' => 'FLOOR CRANE'],
            ['kode' => 'PPL-00684', 'nama' => 'PERKAKAS PENGANGKAT LAINNYA'],
            ['kode' => 'PSST-00685', 'nama' => 'PERKAKAS STANDARD (STANDARD TOOLS)'],
            ['kode' => 'TKS-00686', 'nama' => 'TOOL KIT SET'],
            ['kode' => 'TKB-00687', 'nama' => 'TOOL KIT BOX'],
            ['kode' => 'TCS-00688', 'nama' => 'TOOL CABINET SET'],
            ['kode' => 'KP-00689', 'nama' => 'KUNCI PIPA'],
            ['kode' => 'PS-00690', 'nama' => 'PULLER SET'],
            ['kode' => 'TD-00691', 'nama' => 'TAP DIES'],
            ['kode' => 'G-00692', 'nama' => 'GREEPER'],
            ['kode' => 'ES-00693', 'nama' => 'ENGINE STAND'],
            ['kode' => 'KM-00694', 'nama' => 'KUNCI MOMENT'],
            ['kode' => 'PFD-00695', 'nama' => 'PEMBUAT FISIK (DIESS)'],
            ['kode' => 'TNF-00696', 'nama' => 'TUNGKU NON FERROUS'],
            ['kode' => 'WCPSST-00697', 'nama' => 'WHEEL CHOCK (PERKAKAS STANDARD (STANDARD TOOLS))'],
            ['kode' => 'MS-00698', 'nama' => 'MAINTENANCE STEP'],
            ['kode' => 'CT-00699', 'nama' => 'CRIMPING TOLLS'],
            ['kode' => 'TTKT-00700', 'nama' => 'TOOLKIT TUKANG KAYU TON'],
            ['kode' => 'TTBT-00701', 'nama' => 'TOOLKIT TUKANG BATU TON'],
            ['kode' => 'TTL-00702', 'nama' => 'TOOLKIT TUKANG LISTRIK'],
            ['kode' => 'TP-00703', 'nama' => 'TOOLKIT PEMELIHARAAN'],
            ['kode' => 'TP-00704', 'nama' => 'TOOLKIT PERBENGKELAN'],
            ['kode' => 'TP-00705', 'nama' => 'TOOLKIT PERPIPAAN'],
            ['kode' => 'TOPE-00706', 'nama' => 'TOOL OUTFIT PIONER ELECTRIC'],
            ['kode' => 'TGMS-00707', 'nama' => 'TOOL GENERAL MECHANIC SET'],
            ['kode' => 'TTB-00708', 'nama' => 'TOOLKIT TUKANG BESI'],
            ['kode' => 'TES-00709', 'nama' => 'TOOL ELECTRICAL SET'],
            ['kode' => 'S-00710', 'nama' => 'SAWMIL'],
            ['kode' => 'UPP-00711', 'nama' => 'UNIT PELUMAS PORTABLE'],
            ['kode' => 'SST-00712', 'nama' => 'SCAFOLDING SET & TOOL'],
            ['kode' => 'HF-00713', 'nama' => 'HAND FALLET'],
            ['kode' => 'P-00714', 'nama' => 'PARON'],
            ['kode' => 'CB-00715', 'nama' => 'CYLINDER BEARING'],
            ['kode' => 'PBP-00716', 'nama' => 'PERLENGKAPAN BENGKEL PENGECATAN'],
            ['kode' => 'PSSTL-00717', 'nama' => 'PERKAKAS STANDARD (STANDARD TOOLS) LAINNYA'],
            ['kode' => 'PKST-00718', 'nama' => 'PERKAKAS KHUSUS (SPECIAL TOOLS)'],
            ['kode' => 'KKUE-00719', 'nama' => 'KUNCI KHUSUS UNTUK ENGINE'],
            ['kode' => 'KKABD-00720', 'nama' => 'KUNCI KHUSUS ALAT BESAR DARAT'],
            ['kode' => 'KKABA-00721', 'nama' => 'KUNCI KHUSUS ALAT BESAR APUNG'],
            ['kode' => 'KKCAAD-00722', 'nama' => 'KUNCI KHUSUS CASIS ALAT ANGKUT DARAT'],
            ['kode' => 'KKC-00723', 'nama' => 'KUNCI KHUSUS CASIS'],
            ['kode' => 'KKAAA-00724', 'nama' => 'KUNCI KHUSUS ALAT ANGKUT APUNG'],
            ['kode' => 'KKPM-00725', 'nama' => 'KUNCI KHUSUS PEMBUKA MUR/BAUT'],
            ['kode' => 'KKM-00726', 'nama' => 'KUNCI KHUSUS MOMENT'],
            ['kode' => 'KKABU-00727', 'nama' => 'KUNCI KHUSUS ALAT BESAR UDARA'],
            ['kode' => 'KKCABU-00728', 'nama' => 'KUNCI KHUSUS CASIS ALAT BESAR UDARA'],
            ['kode' => 'DTA-00729', 'nama' => 'DIGITAL TANG AMPERE'],
            ['kode' => 'DT-00730', 'nama' => 'DIGITAL TACHOMETER'],
            ['kode' => 'FK-00731', 'nama' => 'FOOT KLEP'],
            ['kode' => 'CSH-00732', 'nama' => 'CINCIN/KOPLING SLANG HYDRANT'],
            ['kode' => 'KL-00733', 'nama' => 'KUNCI L'],
            ['kode' => 'T-00734', 'nama' => 'TBA'],
            ['kode' => 'PKSTL-00735', 'nama' => 'PERKAKAS KHUSUS (SPECIAL TOOLS) LAINNYA'],
            ['kode' => 'PBK-00736', 'nama' => 'PERKAKAS BENGKEL KERJA'],
            ['kode' => 'G-00737', 'nama' => 'GERGAJI'],
            ['kode' => 'K-00738', 'nama' => 'KETAM'],
            ['kode' => 'B-00739', 'nama' => 'BOR'],
            ['kode' => 'P-00740', 'nama' => 'PAHAT'],
            ['kode' => 'KT-00741', 'nama' => 'KAKAK TUA'],
            ['kode' => 'WP-00742', 'nama' => 'WATER PAS'],
            ['kode' => 'S-00743', 'nama' => 'SIKU'],
            ['kode' => 'P-00744', 'nama' => 'PALU'],
            ['kode' => 'PBKL-00745', 'nama' => 'PERKAKAS BENGKEL KERJA LAINNYA'],
            ['kode' => 'PTB-00746', 'nama' => 'PERALATAN TUKANG BESI'],
            ['kode' => 'T-00747', 'nama' => 'TANGGEM'],
            ['kode' => 'GP-00748', 'nama' => 'GUNTING PLAT'],
            ['kode' => 'LK-00749', 'nama' => 'LANDASAN KENTENG'],
            ['kode' => 'KK-00750', 'nama' => 'KUNCI KAUL'],
            ['kode' => 'GPT-00751', 'nama' => 'GUNTING PLAT TANGAN'],
            ['kode' => 'TK-00752', 'nama' => 'TANG KOMBINASI'],
            ['kode' => 'TP-00753', 'nama' => 'TANG POTONG'],
            ['kode' => 'PK-00754', 'nama' => 'PUKUL KONDE'],
            ['kode' => 'PL-00755', 'nama' => 'PUKUL LENGKUNG'],
            ['kode' => 'PS-00756', 'nama' => 'PUKUL SABIT'],
            ['kode' => 'K-00757', 'nama' => 'KIKIR'],
            ['kode' => 'KP-00758', 'nama' => 'KUNCI PAS'],
            ['kode' => 'TST-00759', 'nama' => 'TANG SENAI & TAP'],
            ['kode' => 'DBO-00760', 'nama' => 'DREI BIASA (OBENG)'],
            ['kode' => 'DKO-00761', 'nama' => 'DREI KEMBANG (OBENG)'],
            ['kode' => 'DKO-00762', 'nama' => 'DREI KETOK (OBENG)'],
            ['kode' => 'SM-00763', 'nama' => 'SEKET MAT'],
            ['kode' => 'JB-00764', 'nama' => 'JANGKA BESI'],
            ['kode' => 'KS-00765', 'nama' => 'KUNCI STANG'],
            ['kode' => 'PTBL-00766', 'nama' => 'PERALATAN TUKANG BESI LAINNYA'],
            ['kode' => 'PTK-00767', 'nama' => 'PERALATAN TUKANG KAYU'],
            ['kode' => 'TB-00768', 'nama' => 'TATAH BIASA'],
            ['kode' => 'TL-00769', 'nama' => 'TATAH LENGKUNG'],
            ['kode' => 'K-00770', 'nama' => 'KAOTA'],
            ['kode' => 'P-00771', 'nama' => 'PETEL'],
            ['kode' => 'P-00772', 'nama' => 'PATAR'],
            ['kode' => 'BE-00773', 'nama' => 'BOR ENGKOL'],
            ['kode' => 'PBK-00774', 'nama' => 'PERLENGKAPAN BENGKEL KAYU'],
            ['kode' => 'PTKL-00775', 'nama' => 'PERALATAN TUKANG KAYU LAINNYA'],
            ['kode' => 'PTK-00776', 'nama' => 'PERALATAN TUKANG KULIT'],
            ['kode' => 'PK-00777', 'nama' => 'PISAU KULIT'],
            ['kode' => 'PS-00778', 'nama' => 'PANDOKAN SEPATU'],
            ['kode' => 'LS-00779', 'nama' => 'LIS SEPATU'],
            ['kode' => 'C-00780', 'nama' => 'COKRO'],
            ['kode' => 'PK-00781', 'nama' => 'PLONG KULIT'],
            ['kode' => 'C-00782', 'nama' => 'CATUT'],
            ['kode' => 'PS-00783', 'nama' => 'PUKUL SEPATU'],
            ['kode' => 'GK-00784', 'nama' => 'GUNTING KULIT'],
            ['kode' => 'GK-00785', 'nama' => 'GUNTING KAIN'],
            ['kode' => 'DMA-00786', 'nama' => 'DREK MATA AYAM'],
            ['kode' => 'U-00787', 'nama' => 'UNCEK'],
            ['kode' => 'PTKL-00788', 'nama' => 'PERALATAN TUKANG KULIT LAINNYA'],
            ['kode' => 'DU-00789', 'nama' => 'DIPAN UKUR'],
            ['kode' => 'MK-00790', 'nama' => 'METERAN KAIN'],
            ['kode' => 'RM-00791', 'nama' => 'ROL METER'],
            ['kode' => 'JB-00792', 'nama' => 'JANGKA BERKAKI'],
            ['kode' => 'PG-00793', 'nama' => 'PATAR GIP'],
            ['kode' => 'PG-00794', 'nama' => 'PISAU GIP'],
            ['kode' => 'PB-00795', 'nama' => 'PARAREL BAR'],
            ['kode' => 'CB-00796', 'nama' => 'CERMIN BESAR'],
            ['kode' => 'TL-00797', 'nama' => 'TANGGA LATIHAN'],
            ['kode' => 'TL-00798', 'nama' => 'TRAP LATIHAN'],
            ['kode' => 'PBKP-00799', 'nama' => 'PERALATAN BENGKEL KHUSUS PELADAM'],
            ['kode' => 'MC-00800', 'nama' => 'MESIN CNC'],
            ['kode' => 'DT-00801', 'nama' => 'DYNAMO TUNGKU'],
            ['kode' => 'MS-00802', 'nama' => 'MESIN SKRAF'],
            ['kode' => 'MBM/KL-00803', 'nama' => 'MESIN BOR MEJA / KAKI LISTRIK'],
            ['kode' => 'PB-00804', 'nama' => 'PALU BESAR'],
            ['kode' => 'MK-00805', 'nama' => 'MESIN KORTER'],
            ['kode' => 'PK-00806', 'nama' => 'PALU KECIL'],
            ['kode' => 'MGDBG-00807', 'nama' => 'MESIN GERINDA DUDUK (BENCH GERINDA)'],
            ['kode' => 'GPK-00808', 'nama' => 'GEGEP PEMOTONG KUKU'],
            ['kode' => 'GPP-00809', 'nama' => 'GEGEP PEMOTONG PAKU'],
            ['kode' => 'PR-00810', 'nama' => 'PISAU RENET'],
            ['kode' => 'PT-00811', 'nama' => 'PELOBANG TAPEL'],
            ['kode' => 'TB-00812', 'nama' => 'TANG BUAYA'],
            ['kode' => 'MBS/PA-00813', 'nama' => 'MESIN BATTERY SET / PENGISI ACCU'],
            ['kode' => 'PBL-00814', 'nama' => 'PERALATAN BENGKEL LAINNYA'],
            ['kode' => 'MBL/M-00815', 'nama' => 'MESIN BLOWER LISTRIK / MEKANIK'],
            ['kode' => 'MS/BM-00816', 'nama' => 'MESIN SIKAT / BRUSH MACHINE'],
            ['kode' => 'MPB-00817', 'nama' => 'MESIN PEMBUKA BAN'],
            ['kode' => 'MSKA-00818', 'nama' => 'MESIN SLEP KRUK AS'],
            ['kode' => 'MASC-00819', 'nama' => 'MESIN ASAH SILIDER COP'],
            ['kode' => 'MGS-00820', 'nama' => 'MESIN GULUNG SPOOL'],
            ['kode' => 'MGP-00821', 'nama' => 'MESIN GULUNG PLAT'],
            ['kode' => 'MPAP-00822', 'nama' => 'MESIN POMPA AIR PMK'],
            ['kode' => 'MAK-00823', 'nama' => 'MESIN ASAH KLEP'],
            ['kode' => 'MT/S-00824', 'nama' => 'MESIN TUSUK / STIK'],
            ['kode' => 'MBLT-00825', 'nama' => 'MESIN BOR LISTRIK TANGAN'],
            ['kode' => 'MN-00826', 'nama' => 'MESIN NIMBLING'],
            ['kode' => 'MGTL-00827', 'nama' => 'MESIN GERINDA TANGAN LISTRIK'],
            ['kode' => 'MPPB/HN-00828', 'nama' => 'MESIN POTONG PLAT BENTUK / HAND NIMBLER'],
            ['kode' => 'UC-00829', 'nama' => 'UNIT CAT'],
            ['kode' => 'COS-00830', 'nama' => 'CUT OFF SAW'],
            ['kode' => 'MAS-00831', 'nama' => 'MESIN ANALISA SYSTEM'],
            ['kode' => 'BLP-00832', 'nama' => 'BLENDER LAS POTONG'],
            ['kode' => 'MCKCW-00833', 'nama' => 'MESIN CUCI KENDARAAN/ CAR WASHER'],
            ['kode' => 'PA-00834', 'nama' => 'PERKAKAS AC'],
            ['kode' => 'PBKPL-00835', 'nama' => 'PERALATAN BENGKEL KHUSUS PELADAM LAINNYA'],
            ['kode' => 'ABTBL-00836', 'nama' => 'ALAT BENGKEL TAK BERMESIN LAINNYA'],
            ['kode' => 'AU-00837', 'nama' => 'ALAT UKUR'],
            ['kode' => 'AUU-00838', 'nama' => 'ALAT UKUR UNIVERSAL'],
            ['kode' => 'AGTG-00839', 'nama' => 'AF GENERATOR TONE GENERATOR'],
            ['kode' => 'ASS-00840', 'nama' => 'AUDIO SIGNAL SOURCE'],
            ['kode' => 'ATS-00841', 'nama' => 'AUDIO TEST SET'],
            ['kode' => 'AMDM-00842', 'nama' => 'AUDIO MORSE & DISTRIBUTOR METER'],
            ['kode' => 'ASO-00843', 'nama' => 'AUDIO SWEEP OSILATOR'],
            ['kode' => 'VV-00844', 'nama' => 'VTVM VOLT'],
            ['kode' => 'IM-00845', 'nama' => 'INDEPENDENCE METER'],
            ['kode' => 'DM-00846', 'nama' => 'DECIBLE METER'],
            ['kode' => 'CT-00847', 'nama' => 'CRT TESTER'],
            ['kode' => 'CTAUU-00848', 'nama' => 'CIRCUIT TESTER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'ECT-00849', 'nama' => 'ELECTRONIC CAPASITOR TESTER'],
            ['kode' => 'IM-00850', 'nama' => 'ILLUMINO METER'],
            ['kode' => 'ITSTI-00851', 'nama' => 'IC TESTER SEMI TEST IV'],
            ['kode' => 'IM-00852', 'nama' => 'IC METER'],
            ['kode' => 'MM-00853', 'nama' => 'MIHVOLT METER'],
            ['kode' => 'MA-00854', 'nama' => 'MULTITESTER & ACCESSORIE'],
            ['kode' => 'MD-00855', 'nama' => 'MULTISESTER DIGITAL'],
            ['kode' => 'PIM-00856', 'nama' => 'PHOTO ILLUMINATION METER'],
            ['kode' => 'TTSI-00857', 'nama' => 'TRANSISTOR TESTER SEMITEST I'],
            ['kode' => 'TTSI-00858', 'nama' => 'TRANSISTOR TESTER SEMITEST II'],
            ['kode' => 'TTSV-00859', 'nama' => 'TRANSISTOR TESTER SEMITEST V'],
            ['kode' => 'TTA-00860', 'nama' => 'TRANSISTOR TESTER AVO'],
            ['kode' => 'VME-00861', 'nama' => 'VOLT METER ELEKTRONIK'],
            ['kode' => 'VMD-00862', 'nama' => 'VOLT METER DIGITAL'],
            ['kode' => 'VMHT-00863', 'nama' => 'VOLT METER HIGT TENSION'],
            ['kode' => 'WBLM-00864', 'nama' => 'WIDW BAND LEVEL METER'],
            ['kode' => 'ADM-00865', 'nama' => 'AUTOMATIC DISTROTION METER'],
            ['kode' => 'PMAA-00866', 'nama' => 'POWER METER AND ACCESSORIES'],
            ['kode' => 'PMAUU-00867', 'nama' => 'PH METER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'QPM-00868', 'nama' => 'QUASI PEAK METER'],
            ['kode' => 'TWM-00869', 'nama' => 'THRULINE WATT METER'],
            ['kode' => 'DMAUU-00870', 'nama' => 'DIGITAL MULTIMETER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'MM-00871', 'nama' => 'MULTI METER'],
            ['kode' => 'MC-00872', 'nama' => 'METER CALIBRATOR'],
            ['kode' => 'MFM-00873', 'nama' => 'MOISE FIGURE METER'],
            ['kode' => 'DA-00874', 'nama' => 'DISTORTION ANALYZER'],
            ['kode' => 'VVMAUU-00875', 'nama' => 'VECTOR VOLT METER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'PGAUU-00876', 'nama' => 'PULSE GENERATOR (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'DGSTSAUU-00877', 'nama' => 'DME GROUND STATION TEST SET (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'USG-00878', 'nama' => 'UHF SIGNAL GENERATOR'],
            ['kode' => 'SOAUU-00879', 'nama' => 'SWEEP OSCILLATOR (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'VSG-00880', 'nama' => 'VHF SIGNAL GENERATOR'],
            ['kode' => 'SA-00881', 'nama' => 'SPEKTRUM ANALYZER'],
            ['kode' => 'TTAUU-00882', 'nama' => 'TUBE TESTER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'DA-00883', 'nama' => 'DOSIMETER & ACCESORIES'],
            ['kode' => 'SMAUU-00884', 'nama' => 'SURVEY METER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'SD-00885', 'nama' => 'SOUND DETECTOR'],
            ['kode' => 'VQT-00886', 'nama' => 'VIDICON QUICK TESTER'],
            ['kode' => 'PFTA-00887', 'nama' => 'PATTERN FOR TV ADJUSTMENT'],
            ['kode' => 'PMC-00888', 'nama' => 'POWER METER CILLIBRATOR'],
            ['kode' => 'T-00889', 'nama' => 'THERMISTOR'],
            ['kode' => 'X-TD-00890', 'nama' => 'X - TAL DETECTOR'],
            ['kode' => 'C-ASL-00891', 'nama' => 'CO - AXIAL SLOT LINE'],
            ['kode' => 'RVM-00892', 'nama' => 'RF VOLT METER'],
            ['kode' => 'FWM-00893', 'nama' => 'FREKQUENCY WAVE METER'],
            ['kode' => 'M-00894', 'nama' => 'MEGGER'],
            ['kode' => 'CAA-00895', 'nama' => 'CO AXIAL ATTENUATOR'],
            ['kode' => 'VCAA-00896', 'nama' => 'VARIABEL CO AXIAL ATTENUATOR'],
            ['kode' => 'DCAUU-00897', 'nama' => 'DIRECTIONAL COUPLER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'PM-00898', 'nama' => 'PIN MODULATOR'],
            ['kode' => 'LTSK-00899', 'nama' => 'LOGIG TROUBLE SHOTING KIT'],
            ['kode' => 'SM-00900', 'nama' => 'SWR METER'],
            ['kode' => 'MP-00901', 'nama' => 'MEMORI PROGRAMMER'],
            ['kode' => 'LSA-00902', 'nama' => 'LOGIG STATC ANALYZER'],
            ['kode' => 'FC-00903', 'nama' => 'FREQUENCY CUONTER'],
            ['kode' => 'UB-00904', 'nama' => 'UNIVERSAL BRIDGE'],
            ['kode' => 'FM-00905', 'nama' => 'FB METER'],
            ['kode' => 'N-00906', 'nama' => 'NOISE'],
            ['kode' => 'RMI-00907', 'nama' => 'RADIATION MONITOR ISOTROPIC'],
            ['kode' => 'PM-00908', 'nama' => 'PHASE METER'],
            ['kode' => 'GPS-00909', 'nama' => 'GLOBAL POSITIONING SYSTEM'],
            ['kode' => 'ICR-00910', 'nama' => 'ILS. CALIBRATION RX.'],
            ['kode' => 'DACS-00911', 'nama' => 'DCP ( ALAT CONTROL ) SENSOR'],
            ['kode' => 'MM-00912', 'nama' => 'MOISTEUR METER'],
            ['kode' => 'RM-00913', 'nama' => 'ROTA METER'],
            ['kode' => 'MPV-00914', 'nama' => 'MINI PHASEC VIEW'],
            ['kode' => 'FI-00915', 'nama' => 'FREQUENCY INVERTER'],
            ['kode' => 'A-00916', 'nama' => 'ACCUMETER'],
            ['kode' => 'TD-00917', 'nama' => 'TEMPERATUR DIGITAL'],
            ['kode' => 'A-00918', 'nama' => 'ARGOMETER'],
            ['kode' => 'DTI-00919', 'nama' => 'DIAL TEST INDICATOR'],
            ['kode' => 'SM-00920', 'nama' => 'SPEED METER'],
            ['kode' => 'SD-00921', 'nama' => 'SPEED DETECTOR'],
            ['kode' => 'TAUU-00922', 'nama' => 'THERMOHYGROMETER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'TC-00923', 'nama' => 'TRAFFIC COUNTER'],
            ['kode' => 'STG-00924', 'nama' => 'STANDAR TEST GAUGE'],
            ['kode' => 'SM-00925', 'nama' => 'SIGMA METER'],
            ['kode' => 'IM-00926', 'nama' => 'IONISASI METER'],
            ['kode' => 'RSS-00927', 'nama' => 'ROTAN SAMPLER SPLITER'],
            ['kode' => 'HM-00928', 'nama' => 'HENRY METER'],
            ['kode' => 'MKH-00929', 'nama' => 'MESIN KOCOK HORISONTAL'],
            ['kode' => 'CM-00930', 'nama' => 'CAPASITOR METER'],
            ['kode' => 'MC-00931', 'nama' => 'MICROPROCESSOR CONDUCTIVITY'],
            ['kode' => 'UOPE-00932', 'nama' => 'UHF OUT PUSTTESSTING EQUIPMENT'],
            ['kode' => 'SLA-00933', 'nama' => 'SHRANGKAGE LIMIT APPARATUS'],
            ['kode' => 'RSG-00934', 'nama' => 'R.F. SIGNAL GENERATOR'],
            ['kode' => 'DP-00935', 'nama' => 'DEWMETER PRINT'],
            ['kode' => 'OS-00936', 'nama' => 'ORBITAL SHAKER'],
            ['kode' => 'VDL-00937', 'nama' => 'VHF/UHF DUMMY LOAD'],
            ['kode' => 'O-00938', 'nama' => 'OZONIZER'],
            ['kode' => 'PWN-00939', 'nama' => 'PSOPHOMETRIC WEIGHTING NETWORK'],
            ['kode' => 'PC-00940', 'nama' => 'PERSONAL CDT'],
            ['kode' => 'PTR-00941', 'nama' => 'PORTABLE TEST RECK'],
            ['kode' => 'RMAUU-00942', 'nama' => 'RADIO METER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'NDWW-00943', 'nama' => 'NMOTOR DRIVE WIRE WROPPER'],
            ['kode' => 'STDA-00944', 'nama' => 'SALINITY TEMP DEPTH ANALIZER'],
            ['kode' => 'DCT-00945', 'nama' => 'DIGITAL CIRCUIT TESTER'],
            ['kode' => 'S-00946', 'nama' => 'SALINOMETER'],
            ['kode' => 'FSM-00947', 'nama' => 'FIELD STRENGTH METER'],
            ['kode' => 'ASS-00948', 'nama' => 'ACIENTIFIC SOUNDEER SYSTEM'],
            ['kode' => 'A-00949', 'nama' => 'ALTERNEATUR'],
            ['kode' => 'SBA-00950', 'nama' => 'SENTER BAWAH AIR'],
            ['kode' => 'MOT-00951', 'nama' => 'MEGA OHM TESTER'],
            ['kode' => 'SPH-00952', 'nama' => 'SIX PLACE HIDROMANIFOLD'],
            ['kode' => 'ITAUU-00953', 'nama' => 'INSULATION TESTER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'SVCD-00954', 'nama' => 'SONICATOR VIRSOIC CALL DISLUPTOR'],
            ['kode' => 'EB-00955', 'nama' => 'ELECTRIC BENCH'],
            ['kode' => 'SFG-00956', 'nama' => 'SWEEP FUNCTION GENERATOR'],
            ['kode' => 'L-00957', 'nama' => 'LOADMETER'],
            ['kode' => 'SUSDSA-00958', 'nama' => 'SYSTEM UV STERELISASI DAN SIRKULASI AI'],
            ['kode' => 'CT-00959', 'nama' => 'COUNTER TESTER'],
            ['kode' => 'SFCOD-00960', 'nama' => 'SYSTEM FOR CHEMICAL OXYGEN DEMOND'],
            ['kode' => 'TDSUWV-00961', 'nama' => 'THE DACOR SEASPRINT UNDER WATER VEHICLE'],
            ['kode' => 'TU-00962', 'nama' => 'TITRATION UNIT'],
            ['kode' => 'UCAUU-00963', 'nama' => 'ULTRASONIC CLEANER (ALAT UKUR UNIVERSAL)'],
            ['kode' => 'WAK-00964', 'nama' => 'WATER ANALYSIS KIT'],
            ['kode' => 'WM-00965', 'nama' => 'WHEEL METER'],
            ['kode' => 'PP-00966', 'nama' => 'PROYECTION POLARISCOPE'],
            ['kode' => 'CT-00967', 'nama' => 'CDMA/GSM TEST'],
            ['kode' => 'AS-00968', 'nama' => 'ANTENNA SELECTOR'],
            ['kode' => 'LPA-00969', 'nama' => 'LOG PERIODIC ANTENNA'],
            ['kode' => 'AUS-00970', 'nama' => 'ALAT UKUR SIGMAT'],
            ['kode' => 'AUUL-00971', 'nama' => 'ALAT UKUR UNIVERSAL LAINNYA'],
            ['kode' => 'UT-00972', 'nama' => 'UNIVERSAL TESTER'],
            ['kode' => 'FCUT-00973', 'nama' => 'FREQUENCY COUNTER (UNIVERSAL TESTER)'],
            ['kode' => 'IRMM-00974', 'nama' => 'INSULATION RES METER MOD'],
            ['kode' => 'NDM-00975', 'nama' => 'NOISE & DISTORTION METER'],
            ['kode' => 'ODM-00976', 'nama' => 'OSCILATOR DISTORTION METER'],
            ['kode' => 'OTS-00977', 'nama' => 'OSCILATOR TEST SIGNAL'],
            ['kode' => 'OWB-00978', 'nama' => 'OSCILATOR WIDW BAND'],
            ['kode' => 'OS-00979', 'nama' => 'OSCILATOR SWEEP'],
            ['kode' => 'PEM-00980', 'nama' => 'PRECISION ENCODER MONITOR'],
            ['kode' => 'PTU-00981', 'nama' => 'PLAMBICON TEST UNIT'],
            ['kode' => 'SUT-00982', 'nama' => 'SCANNER (UNIVERSAL TESTER)'],
            ['kode' => 'TIU-00983', 'nama' => 'TIME INTERVAL UNIT'],
            ['kode' => 'UCUT-00984', 'nama' => 'UNIVERSAL COUNTER (UNIVERSAL TESTER)'],
            ['kode' => 'VNM-00985', 'nama' => 'VIDEO NOISE METER'],
            ['kode' => 'AM-00986', 'nama' => 'ADMINTANCE METER'],
            ['kode' => 'AB-00987', 'nama' => 'ADMINTANCE BRIDE'],
            ['kode' => 'FM-00988', 'nama' => 'FIELDSTRENGTH METER'],
            ['kode' => 'RB-00989', 'nama' => 'RF BRIDGE'],
            ['kode' => 'RPBA-00990', 'nama' => 'RF PUSH BUTTON ATTENUATOR'],
            ['kode' => 'VASNDA-00991', 'nama' => 'VISION AND SOUND NYQUIST DEMODULATOR AMF'],
            ['kode' => 'VSR-00992', 'nama' => 'V.S.W.R STANDING REVIEW'],
            ['kode' => 'DFM-00993', 'nama' => 'DIGITAL FREQUENCE METER'],
            ['kode' => 'VQT-00994', 'nama' => 'VINDICAM QUICK TESTER'],
            ['kode' => 'CA-00995', 'nama' => 'COAXIAL ATT'],
            ['kode' => 'VCA-00996', 'nama' => 'VARIABLE COAXIAL ATT'],
            ['kode' => 'LPUT-00997', 'nama' => 'LOGIC PROBE (UNIVERSAL TESTER)'],
            ['kode' => 'SMUT-00998', 'nama' => 'SURVEY METER (UNIVERSAL TESTER)'],
            ['kode' => 'LC-00999', 'nama' => 'LOGIC COMPARATOR'],
            ['kode' => 'UTL-01000', 'nama' => 'UNIVERSAL TESTER LAINNYA'],
            ['kode' => 'AU-01001', 'nama' => 'ALAT UKUR/PEMBANDING'],
            ['kode' => 'UJAPSUP-01002', 'nama' => 'UKURAN JOHANSON (ALAT PEMBANDING STANDAR UKURAN PANJANG)'],
            ['kode' => 'MIDPSPDR-01003', 'nama' => 'MICRO INDICATOR (DENGAN PERLENGKAPAN SUPARTO POINTERS DAN REVOLV'],
            ['kode' => 'PMI-01004', 'nama' => 'PERLENGKAPAN MICRO INDICATOR'],
            ['kode' => 'PV-01005', 'nama' => 'PSYCOMETER VANLAMBRECHT'],
            ['kode' => 'P-01006', 'nama' => 'PSYCOMETER'],
            ['kode' => 'BL-01007', 'nama' => 'BAROMETER LOGAM'],
            ['kode' => 'BM-01008', 'nama' => 'BAROMETER MERCURY'],
            ['kode' => 'MUM-01009', 'nama' => 'MANOMETER UNTUK MESIN'],
            ['kode' => 'MP-01010', 'nama' => 'MONOTOR PRECISI'],
            ['kode' => 'APMDP-01011', 'nama' => 'ALAT PEMERIKSA MANOMETER ( DENGAN PERLENGKAPAN )'],
            ['kode' => 'APZC-01012', 'nama' => 'ALAT PEMERIKSAAN ZAT CAIR'],
            ['kode' => 'TS-01013', 'nama' => 'TERMOMETER STANDAR'],
            ['kode' => 'TGT0DSD1-01014', 'nama' => 'TERMOMETER GOVERMEN TESTER 0 DERAJAT SAMPAI DENGAN 100 DERAJAT C'],
            ['kode' => 'TPPT-01015', 'nama' => 'THERMOSTAT ( PENGUJI PEMERIKSAAN TERMOMETER )'],
            ['kode' => 'JUML-01016', 'nama' => 'JAM UKUR ( MEET LOCK )'],
            ['kode' => 'HT-01017', 'nama' => 'HARDNES TESTER'],
            ['kode' => 'S-01018', 'nama' => 'STOPWATCH'],
            ['kode' => 'L-01019', 'nama' => 'LOUP'],
            ['kode' => 'PAU-01020', 'nama' => 'PLANIMETER (ALAT UKUR/PEMBANDING)'],
            ['kode' => 'MB-01021', 'nama' => 'METRA BLOCK'],
            ['kode' => 'LBP-01022', 'nama' => 'LEMARI BAJA PENGERING'],
            ['kode' => 'SU-01023', 'nama' => 'SANBLAS UNIT'],
            ['kode' => 'APTTB-01024', 'nama' => 'ALAT PEMERIKSAAN TIMBANGAN TEKANAN BERODA'],
            ['kode' => 'SIB-01025', 'nama' => 'STELAN INSTRUMEN BOURJE'],
            ['kode' => 'LUMSNPS-01026', 'nama' => 'LAMPU UNTUK MENERANGI SKALA NERACA PAKAI STANDAR'],
            ['kode' => 'AS2-2K-01027', 'nama' => 'AVOMETER SU 20 - 20 K'],
            ['kode' => 'T1W-01028', 'nama' => 'TRAPPO 1.000 WATT'],
            ['kode' => 'TS-01029', 'nama' => 'TOOL SET'],
            ['kode' => 'LCL-01030', 'nama' => 'LANDASAN CAP LENGKAP'],
            ['kode' => 'KTGD-01031', 'nama' => 'KAKI TIGA GANTUNGAN DACIN'],
            ['kode' => 'APTB-01032', 'nama' => 'ALAT PENDATAR TAKARAN BENSIN'],
            ['kode' => 'TP/S-01033', 'nama' => 'TANG PLOMBIR / SEGEL'],
            ['kode' => 'EB-01034', 'nama' => 'EXICATOR BESAR'],
            ['kode' => 'EK-01035', 'nama' => 'EXICATOR KECIL'],
            ['kode' => 'DS3-01036', 'nama' => 'DESICATOR ( SIZE ) 3'],
            ['kode' => 'DS4-01037', 'nama' => 'DESICATOR ( SIZE ) 4'],
            ['kode' => 'BASD2L-01038', 'nama' => 'BOTOL AIR SALING DARI 25 LITER'],
            ['kode' => 'P-01039', 'nama' => 'PICNOMETER'],
            ['kode' => 'DH-01040', 'nama' => 'DESIMETER ( HIDROMETER )'],
            ['kode' => 'TTV-01041', 'nama' => 'TELESCOPE TILE VARIEBLE'],
            ['kode' => 'OSUPK-01042', 'nama' => 'OPTICAL STREAN ( UNTUK PEMERIKSAAN KACA )'],
            ['kode' => 'OTGPTD-01043', 'nama' => 'OPTOCAL TEKNIS GANGE ( PENGUKUR TEBAL DINDING )'],
            ['kode' => 'LC5K-01044', 'nama' => 'LIFTER CAPASITAS 500 KG'],
            ['kode' => 'TT-01045', 'nama' => 'TAXIMETER TESTER'],
            ['kode' => 'ST-01046', 'nama' => 'SPEDOMETER TESTER'],
            ['kode' => 'SGB-01047', 'nama' => 'STANDARD GUAGE BLOCKS'],

        ];
        foreach ($data as $item) {
            InvKategoriPeralatan::create(
                [
                    'kode' => $item['kode'],
                    'nama' => $item['nama']
                ]
            );
        }
    }
}