<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InvKategoriAsset;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class InvKategoriAssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['kode' => 'ATL-00001', 'nama' => 'ASET TETAP LAINNYA'],
            ['kode' => 'BP-00002', 'nama' => 'BAHAN PERPUSTAKAAN'],
            ['kode' => 'BPT-00003', 'nama' => 'BAHAN PERPUSTAKAAN TERCETAK'],
            ['kode' => 'B-00004', 'nama' => 'BUKU'],
            ['kode' => 'M-00005', 'nama' => 'MONOGRAF'],
            ['kode' => 'R-00006', 'nama' => 'REFERENSI'],
            ['kode' => 'BL-00007', 'nama' => 'BUKU LAINNYA'],
            ['kode' => 'S-00008', 'nama' => 'SERIAL'],
            ['kode' => 'SK-00009', 'nama' => 'SURAT KABAR'],
            ['kode' => 'M-00010', 'nama' => 'MAJALAH'],
            ['kode' => 'B-00011', 'nama' => 'BULETIN'],
            ['kode' => 'L-00012', 'nama' => 'LAPORAN'],
            ['kode' => 'SL-00013', 'nama' => 'SERIAL LAINNYA'],
            ['kode' => 'TL-00014', 'nama' => 'TERCETAK LAINNYA'],
            ['kode' => 'BPTL-00015', 'nama' => 'BAHAN PERPUSTAKAAN TERCETAK LAINNYA'],
            ['kode' => 'BPTDBM-00016', 'nama' => 'BAHAN PERPUSTAKAAN TEREKAM DAN BENTUK MIKRO'],
            ['kode' => 'AV-00017', 'nama' => 'AUDIO VISUAL'],
            ['kode' => 'K-00018', 'nama' => 'KASET'],
            ['kode' => 'V-00019', 'nama' => 'VIDEO'],
            ['kode' => 'C-00020', 'nama' => 'CD/VCD/DVD/LD'],
            ['kode' => 'PF-00021', 'nama' => 'PITA FILM'],
            ['kode' => 'PS-00022', 'nama' => 'PITA SUARA'],
            ['kode' => 'PH-00023', 'nama' => 'PIRINGAN HITAM'],
            ['kode' => 'PD-00024', 'nama' => 'PETA DIGITAL'],
            ['kode' => 'AVL-00025', 'nama' => 'AUDIO VISUAL LAINNYA'],
            ['kode' => 'BMM-00026', 'nama' => 'BENTUK MIKRO (MICROFORM)'],
            ['kode' => 'M-00027', 'nama' => 'MIKROFILM'],
            ['kode' => 'M-00028', 'nama' => 'MIKROFISCH'],
            ['kode' => 'S-00029', 'nama' => 'SLIDE'],
            ['kode' => 'BML-00030', 'nama' => 'BENTUK MIKRO/MIKROFORM LAINNYA'],
            ['kode' => 'TDBML-00031', 'nama' => 'TEREKAM DAN BENTUK MIKRO LAINNYA'],
            ['kode' => 'BPTDBML-00032', 'nama' => 'BAHAN PERPUSTAKAAN TEREKAM DAN BENTUK MIKRO LAINNYA'],
            ['kode' => 'BK-00033', 'nama' => 'BAHAN KARTOGRAFI'],
            ['kode' => 'PM-00034', 'nama' => 'PETA (MAP)'],
            ['kode' => 'A-00035', 'nama' => 'ATLAS'],
            ['kode' => 'BP-00036', 'nama' => 'BLUE PRINT'],
            ['kode' => 'BDG-00037', 'nama' => 'BOLA DUNIA (GLOBE)'],
            ['kode' => 'BKL-00038', 'nama' => 'BAHAN KARTOGRAFI LAINNYA'],
            ['kode' => 'NM/A-00039', 'nama' => 'NASKAH (MANUSKRIP) / ASLI'],
            ['kode' => 'NBK-00040', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN KERTAS'],
            ['kode' => 'NBD-00041', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN DAUN'],
            ['kode' => 'NBK-00042', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN KAYU'],
            ['kode' => 'NBB-00043', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN BAMBU'],
            ['kode' => 'NBKK-00044', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN KULIT KAYU'],
            ['kode' => 'NBKB-00045', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN KULIT BINATANG'],
            ['kode' => 'NBT-00046', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN TULANG/TANDUK'],
            ['kode' => 'NBT-00047', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN TEMPURUNG'],
            ['kode' => 'NBL-00048', 'nama' => 'NASKAH/MANUSKRIP BERBAHAN LAINNYA'],
            ['kode' => 'LDU-00049', 'nama' => 'LUKISAN DAN UKIRAN'],
            ['kode' => 'LK-00050', 'nama' => 'LUKISAN KANVAS'],
            ['kode' => 'UKDS-00051', 'nama' => 'UKIRAN KAYU DAN SEJENISNYA'],
            ['kode' => 'ULDS-00052', 'nama' => 'UKIRAN LOGAM DAN SEJENISNYA'],
            ['kode' => 'UBDS-00053', 'nama' => 'UKIRAN BATU DAN SEJENISNYA'],
            ['kode' => 'UDLL-00054', 'nama' => 'UKIRAN DAN LUKISAN LAINNYA'],
            ['kode' => 'BBK-00055', 'nama' => 'BARANG BERCORAK KESENIAN/KEBUDAYAAN/OLAHRAGA'],
            ['kode' => 'BBK-00056', 'nama' => 'BARANG BERCORAK KESENIAN'],
            ['kode' => 'AM-00057', 'nama' => 'ALAT MUSIK'],
            ['kode' => 'AMT-00058', 'nama' => 'ALAT MUSIK TRADISIONAL/DAERAH'],
            ['kode' => 'AMM-00059', 'nama' => 'ALAT MUSIK MODERN/BAND'],
            ['kode' => 'AML-00060', 'nama' => 'ALAT MUSIK LAINNYA'],
            ['kode' => 'L-00061', 'nama' => 'LUKISAN'],
            ['kode' => 'LCA-00062', 'nama' => 'LUKISAN CAT AIR'],
            ['kode' => 'S/T-00063', 'nama' => 'SULAMAN / TEMPELAN'],
            ['kode' => 'LCM-00064', 'nama' => 'LUKISAN CAT MINYAK'],
            ['kode' => 'LB-00065', 'nama' => 'LUKISAN BULU'],
            ['kode' => 'SR-00066', 'nama' => 'SENI RELIEF'],
            ['kode' => 'LL-00067', 'nama' => 'LUKISAN LAINNYA'],
            ['kode' => 'APK-00068', 'nama' => 'ALAT PERAGA KESENIAN'],
            ['kode' => 'WG-00069', 'nama' => 'WAYANG GOLEK'],
            ['kode' => 'WK-00070', 'nama' => 'WAYANG KULIT'],
            ['kode' => 'APKL-00071', 'nama' => 'ALAT PERAGA KESENIAN LAINNYA'],
            ['kode' => 'BBKL-00072', 'nama' => 'BARANG BERCORAK KESENIAN LAINNYA'],
            ['kode' => 'ABK-00073', 'nama' => 'ALAT BERCORAK KEBUDAYAAN'],
            ['kode' => 'P-00074', 'nama' => 'PAHATAN'],
            ['kode' => 'PB-00075', 'nama' => 'PAHATAN BATU'],
            ['kode' => 'PK-00076', 'nama' => 'PAHATAN KAYU'],
            ['kode' => 'PL-00077', 'nama' => 'PAHATAN LOGAM'],
            ['kode' => 'PL-00078', 'nama' => 'PAHATAN LAINNYA'],
            ['kode' => 'M-00079', 'nama' => 'MAKET/MINIATUR/REPLIKA'],
            ['kode' => 'FD-00080', 'nama' => 'FOTO DOKUMEN'],
            ['kode' => 'NK-00081', 'nama' => 'NASKAH KUNO'],
            ['kode' => 'MUN-00082', 'nama' => 'MATA UANG/ NUMISMATIK'],
            ['kode' => 'P-00083', 'nama' => 'PERHIASAN'],
            ['kode' => 'BKG-00084', 'nama' => 'BARANG KERAMIK/ GERABAH'],
            ['kode' => 'AP-00085', 'nama' => 'ARCA/ PATUNG'],
            ['kode' => 'BKU-00086', 'nama' => 'BENDA KUNO/ UNIK'],
            ['kode' => 'F-00087', 'nama' => 'FOSIL'],
            ['kode' => 'M-00088', 'nama' => 'MUMY'],
            ['kode' => 'MDFDL-00089', 'nama' => 'MAKET DAN FOTO DOKUMEN LAINNYA'],
            ['kode' => 'ABKL-00090', 'nama' => 'ALAT BERCORAK KEBUDAYAAN LAINNYA'],
            ['kode' => 'TPBOR-00091', 'nama' => 'TANDA PENGHARGAAN BIDANG OLAH RAGA'],
            ['kode' => 'TP-00092', 'nama' => 'TANDA PENGHARGAAN'],
            ['kode' => 'P-00093', 'nama' => 'PIALA'],
            ['kode' => 'M-00094', 'nama' => 'MEDALI'],
            ['kode' => 'P-00095', 'nama' => 'PIAGAM'],
            ['kode' => 'TPL-00096', 'nama' => 'TANDA PENGHARGAAN LAINNYA'],
            ['kode' => 'TPBORL-00097', 'nama' => 'TANDA PENGHARGAAN BIDANG OLAH RAGA LAINNYA'],
            ['kode' => 'H-00098', 'nama' => 'HEWAN'],
            ['kode' => 'HP-00099', 'nama' => 'HEWAN PIARAAN'],
            ['kode' => 'HP-00100', 'nama' => 'HEWAN PENGAMAN'],
            ['kode' => 'AP-00101', 'nama' => 'ANJING PELACAK'],
            ['kode' => 'AP-00102', 'nama' => 'ANJING PENJAGA'],
            ['kode' => 'HPL-00103', 'nama' => 'HEWAN PENGAMAN LAINNYA'],
            ['kode' => 'HP-00104', 'nama' => 'HEWAN PENGANGKUT'],
            ['kode' => 'G-00105', 'nama' => 'GAJAH'],
            ['kode' => 'KHP-00106', 'nama' => 'KUDA (HEWAN PENGANGKUT)'],
            ['kode' => 'HPL-00107', 'nama' => 'HEWAN PENGANGKUT LAINNYA'],
            ['kode' => 'HPL-00108', 'nama' => 'HEWAN PIARAAN LAINNYA'],
            ['kode' => 'T-00109', 'nama' => 'TERNAK'],
            ['kode' => 'TP-00110', 'nama' => 'TERNAK POTONG'],
            ['kode' => 'B-00111', 'nama' => 'BABI'],
            ['kode' => 'D-00112', 'nama' => 'DOMBA'],
            ['kode' => 'K-00113', 'nama' => 'KAMBING'],
            ['kode' => 'K-00114', 'nama' => 'KERBAU'],
            ['kode' => 'SP-00115', 'nama' => 'SAPI POTONG'],
            ['kode' => 'TPL-00116', 'nama' => 'TERNAK POTONG LAINNYA'],
            ['kode' => 'TP-00117', 'nama' => 'TERNAK PERAH'],
            ['kode' => 'SP-00118', 'nama' => 'SAPI PERAH'],
            ['kode' => 'DP-00119', 'nama' => 'DOMBA PERAH'],
            ['kode' => 'KP-00120', 'nama' => 'KAMBING PERAH'],
            ['kode' => 'TPL-00121', 'nama' => 'TERNAK PERAH LAINNYA'],
            ['kode' => 'TU-00122', 'nama' => 'TERNAK UNGGAS'],
            ['kode' => 'A-00123', 'nama' => 'AYAM'],
            ['kode' => 'B-00124', 'nama' => 'BURUNG'],
            ['kode' => 'I-00125', 'nama' => 'ITIK'],
            ['kode' => 'TUL-00126', 'nama' => 'TERNAK UNGGAS LAINNYA'],
            ['kode' => 'TL-00127', 'nama' => 'TERNAK LAINNYA'],
            ['kode' => 'HL-00128', 'nama' => 'HEWAN LAINNYA'],
            ['kode' => 'I-00129', 'nama' => 'IKAN'],
            ['kode' => 'IBPB-00130', 'nama' => 'IKAN BERSIRIP (PISCES/IKAN BERSIRIP)'],
            ['kode' => 'IB-00131', 'nama' => 'IKAN BUDIDAYA'],
            ['kode' => 'IATB-00132', 'nama' => 'IKAN AIR TAWAR BUDIDAYA'],
            ['kode' => 'IALB-00133', 'nama' => 'IKAN AIR LAUT BUDIDAYA'],
            ['kode' => 'IAPB-00134', 'nama' => 'IKAN AIR PAYAU BUDIDAYA'],
            ['kode' => 'IHATB-00135', 'nama' => 'IKAN HIAS AIR TAWAR BUDIDAYA'],
            ['kode' => 'IHAPB-00136', 'nama' => 'IKAN HIAS AIR PAYAU/LAUT BUDIDAYA'],
            ['kode' => 'IBL-00137', 'nama' => 'IKAN BUDIDAYA LAINNYA'],
            ['kode' => 'U-00138', 'nama' => 'UDANG'],
            ['kode' => 'R-00139', 'nama' => 'RAJUNGAN'],
            ['kode' => 'K-00140', 'nama' => 'KEPITING'],
            ['kode' => 'K-00141', 'nama' => 'KERANG'],
            ['kode' => 'T-00142', 'nama' => 'TIRAM'],
            ['kode' => 'CC-00143', 'nama' => 'CUMI-CUMI'],
            ['kode' => 'G-00144', 'nama' => 'GURITA'],
            ['kode' => 'S-00145', 'nama' => 'SIPUT'],
            ['kode' => 'CUUDS-00146', 'nama' => 'COELENTERATA (UBUR-UBUR DAN SEBANGSANYA)'],
            ['kode' => 'CBUUDS-00147', 'nama' => 'COELENTERATA BUDIDAYA (UBUR-UBUR DAN SEBANGSANYA)'],
            ['kode' => 'UUB-00148', 'nama' => 'UBUR-UBUR BUDIDAYA'],
            ['kode' => 'CUUDSL-00149', 'nama' => 'COELENTERATA (UBUR-UBUR DAN SEBANGSANYA) LAINNYA'],
            ['kode' => 'T-00150', 'nama' => 'TERIPANG'],
            ['kode' => 'BB-00151', 'nama' => 'BULU BABI'],
            ['kode' => 'AKDS-00152', 'nama' => 'AMPHIBIA (KODOK DAN SEBANGSANYA)'],
            ['kode' => 'ABKDS-00153', 'nama' => 'AMPHIBIA BUDIDAYA (KODOK DAN SEBANGSANYA)'],
            ['kode' => 'K-00154', 'nama' => 'KODOK'],
            ['kode' => 'SK-00155', 'nama' => 'SEBANGSA KODOK'],
            ['kode' => 'AKDSL-00156', 'nama' => 'AMPHIBIA (KODOK DAN SEBANGSANYA) LAINNYA'],
            ['kode' => 'ARLDTTL-00157', 'nama' => 'ALGAE (RUMPUT LAUT DAN TUMBUH-TUMBUHAN LAIN YANG HIDUP DI DALAM AIR)'],
            ['kode' => 'ABRLDTT-00158', 'nama' => 'ALGAE BUDIDAYA (RUMPUT LAUT DAN TUMBUH-TUMBUHAN LAIN YANG HIDUP DI DALAM AIR)'],

        ];
        foreach ($data as $item) {
            InvKategoriAsset::create([
                'kode' => $item['kode'],
                'nama' => $item['nama']
            ]);
        }
    }
}